/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  HealthHealthGet200
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getHealth = () => {
/**
 * @summary Health
 */
const healthHealthGet = (

 options?: SecondParameter<typeof customInstance<HealthHealthGet200>>,) => {
      return customInstance<HealthHealthGet200>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  return {healthHealthGet}};
export type HealthHealthGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHealth>['healthHealthGet']>>>
