/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  DiagnosisCodeCreate,
  DiagnosisCodeRead,
  DiagnosisCodeUpdate,
  HospitalizationDiagnosisCreate,
  HospitalizationDiagnosisRead,
  HospitalizationDiagnosisUpdate,
  ListDiagnosesApiV1DiagnosesGetParams,
  ListHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGetParams
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDiagnoses = () => {
/**
 * Catálogo CIE-10. ``search`` busca por código o por texto del diagnóstico.
 *
 * Son más de catorce mil códigos: la respuesta viene acotada por ``limit``.
 * @summary List Diagnoses
 */
const listDiagnosesApiV1DiagnosesGet = (
    params?: ListDiagnosesApiV1DiagnosesGetParams,
 options?: SecondParameter<typeof customInstance<DiagnosisCodeRead[]>>,) => {
      return customInstance<DiagnosisCodeRead[]>(
      {url: `/api/v1/diagnoses`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Create Diagnosis
 */
const createDiagnosisApiV1DiagnosesPost = (
    diagnosisCodeCreate: DiagnosisCodeCreate,
 options?: SecondParameter<typeof customInstance<DiagnosisCodeRead>>,) => {
      return customInstance<DiagnosisCodeRead>(
      {url: `/api/v1/diagnoses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: diagnosisCodeCreate
    },
      options);
    }
  /**
 * El código es la identidad del diagnóstico fuera del sistema.
 * @summary Get Diagnosis By Code
 */
const getDiagnosisByCodeApiV1DiagnosesByCodeCodeGet = (
    code: string,
 options?: SecondParameter<typeof customInstance<DiagnosisCodeRead>>,) => {
      return customInstance<DiagnosisCodeRead>(
      {url: `/api/v1/diagnoses/by-code/${code}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get Diagnosis
 */
const getDiagnosisApiV1DiagnosesDiagnosisIdGet = (
    diagnosisId: string,
 options?: SecondParameter<typeof customInstance<DiagnosisCodeRead>>,) => {
      return customInstance<DiagnosisCodeRead>(
      {url: `/api/v1/diagnoses/${diagnosisId}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update Diagnosis
 */
const updateDiagnosisApiV1DiagnosesDiagnosisIdPut = (
    diagnosisId: string,
    diagnosisCodeUpdate: DiagnosisCodeUpdate,
 options?: SecondParameter<typeof customInstance<DiagnosisCodeRead>>,) => {
      return customInstance<DiagnosisCodeRead>(
      {url: `/api/v1/diagnoses/${diagnosisId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: diagnosisCodeUpdate
    },
      options);
    }
  /**
 * Para sacar de circulación un código que ya se usó, desactivarlo en lugar de
 * borrarlo.
 * @summary Delete Diagnosis
 */
const deleteDiagnosisApiV1DiagnosesDiagnosisIdDelete = (
    diagnosisId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/diagnoses/${diagnosisId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Diagnósticos de la internación: los de ingreso y los de egreso.
 * @summary List Hospitalization Diagnoses
 */
const listHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGet = (
    hospitalizationId: string,
    params?: ListHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGetParams,
 options?: SecondParameter<typeof customInstance<HospitalizationDiagnosisRead[]>>,) => {
      return customInstance<HospitalizationDiagnosisRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/diagnoses`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Asienta un diagnóstico del catálogo CIE-10. Uno solo puede ser el principal de cada
 * momento, y con el alta médica dada solo lo corrige un administrador.
 * @summary Add Hospitalization Diagnosis
 */
const addHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesPost = (
    hospitalizationId: string,
    hospitalizationDiagnosisCreate: HospitalizationDiagnosisCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationDiagnosisRead>>,) => {
      return customInstance<HospitalizationDiagnosisRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/diagnoses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationDiagnosisCreate
    },
      options);
    }
  /**
 * Corrige el rol, el profesional o las notas. Para cambiar el código, quítelo y
 * asiente el que corresponde.
 * @summary Update Hospitalization Diagnosis
 */
const updateHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdPut = (
    hospitalizationId: string,
    entryId: string,
    hospitalizationDiagnosisUpdate: HospitalizationDiagnosisUpdate,
 options?: SecondParameter<typeof customInstance<HospitalizationDiagnosisRead>>,) => {
      return customInstance<HospitalizationDiagnosisRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/diagnoses/${entryId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationDiagnosisUpdate
    },
      options);
    }
  /**
 * @summary Remove Hospitalization Diagnosis
 */
const removeHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdDelete = (
    hospitalizationId: string,
    entryId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/diagnoses/${entryId}`, method: 'DELETE'
    },
      options);
    }
  return {listDiagnosesApiV1DiagnosesGet,createDiagnosisApiV1DiagnosesPost,getDiagnosisByCodeApiV1DiagnosesByCodeCodeGet,getDiagnosisApiV1DiagnosesDiagnosisIdGet,updateDiagnosisApiV1DiagnosesDiagnosisIdPut,deleteDiagnosisApiV1DiagnosesDiagnosisIdDelete,listHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGet,addHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesPost,updateHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdPut,removeHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdDelete}};
export type ListDiagnosesApiV1DiagnosesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['listDiagnosesApiV1DiagnosesGet']>>>
export type CreateDiagnosisApiV1DiagnosesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['createDiagnosisApiV1DiagnosesPost']>>>
export type GetDiagnosisByCodeApiV1DiagnosesByCodeCodeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['getDiagnosisByCodeApiV1DiagnosesByCodeCodeGet']>>>
export type GetDiagnosisApiV1DiagnosesDiagnosisIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['getDiagnosisApiV1DiagnosesDiagnosisIdGet']>>>
export type UpdateDiagnosisApiV1DiagnosesDiagnosisIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['updateDiagnosisApiV1DiagnosesDiagnosisIdPut']>>>
export type DeleteDiagnosisApiV1DiagnosesDiagnosisIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['deleteDiagnosisApiV1DiagnosesDiagnosisIdDelete']>>>
export type ListHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['listHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGet']>>>
export type AddHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['addHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesPost']>>>
export type UpdateHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['updateHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdPut']>>>
export type RemoveHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDiagnoses>['removeHospitalizationDiagnosisApiV1HospitalizationsHospitalizationIdDiagnosesEntryIdDelete']>>>
