/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGetParams,
  HospitalizationPracticeCancelCreate,
  HospitalizationPracticeCreate,
  HospitalizationPracticePerformCreate,
  HospitalizationPracticeRead,
  ListPracticeTariffsApiV1PracticesPracticeIdTariffsGetParams,
  ListPracticesApiV1PracticesGetParams,
  MedicalPracticeCreate,
  MedicalPracticeRead,
  MedicalPracticeTariffCreate,
  MedicalPracticeTariffRead,
  MedicalPracticeTariffUpdate,
  MedicalPracticeUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getPractices = () => {
/**
 * Catálogo de prácticas. ``search`` busca por código o nombre.
 * @summary List Practices
 */
const listPracticesApiV1PracticesGet = (
    params?: ListPracticesApiV1PracticesGetParams,
 options?: SecondParameter<typeof customInstance<MedicalPracticeRead[]>>,) => {
      return customInstance<MedicalPracticeRead[]>(
      {url: `/api/v1/practices`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Create Practice
 */
const createPracticeApiV1PracticesPost = (
    medicalPracticeCreate: MedicalPracticeCreate,
 options?: SecondParameter<typeof customInstance<MedicalPracticeRead>>,) => {
      return customInstance<MedicalPracticeRead>(
      {url: `/api/v1/practices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: medicalPracticeCreate
    },
      options);
    }
  /**
 * @summary Get Practice
 */
const getPracticeApiV1PracticesPracticeIdGet = (
    practiceId: string,
 options?: SecondParameter<typeof customInstance<MedicalPracticeRead>>,) => {
      return customInstance<MedicalPracticeRead>(
      {url: `/api/v1/practices/${practiceId}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update Practice
 */
const updatePracticeApiV1PracticesPracticeIdPut = (
    practiceId: string,
    medicalPracticeUpdate: MedicalPracticeUpdate,
 options?: SecondParameter<typeof customInstance<MedicalPracticeRead>>,) => {
      return customInstance<MedicalPracticeRead>(
      {url: `/api/v1/practices/${practiceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: medicalPracticeUpdate
    },
      options);
    }
  /**
 * @summary Delete Practice
 */
const deletePracticeApiV1PracticesPracticeIdDelete = (
    practiceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/practices/${practiceId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Practice Tariffs
 */
const listPracticeTariffsApiV1PracticesPracticeIdTariffsGet = (
    practiceId: string,
    params?: ListPracticeTariffsApiV1PracticesPracticeIdTariffsGetParams,
 options?: SecondParameter<typeof customInstance<MedicalPracticeTariffRead[]>>,) => {
      return customInstance<MedicalPracticeTariffRead[]>(
      {url: `/api/v1/practices/${practiceId}/tariffs`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Create Practice Tariff
 */
const createPracticeTariffApiV1PracticesPracticeIdTariffsPost = (
    practiceId: string,
    medicalPracticeTariffCreate: MedicalPracticeTariffCreate,
 options?: SecondParameter<typeof customInstance<MedicalPracticeTariffRead>>,) => {
      return customInstance<MedicalPracticeTariffRead>(
      {url: `/api/v1/practices/${practiceId}/tariffs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: medicalPracticeTariffCreate
    },
      options);
    }
  /**
 * Valor vigente de la práctica: primero el del plan, luego el del financiador y
 * por último el institucional.
 * @summary Get Effective Practice Tariff
 */
const getEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGet = (
    practiceId: string,
    params?: GetEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGetParams,
 options?: SecondParameter<typeof customInstance<MedicalPracticeTariffRead>>,) => {
      return customInstance<MedicalPracticeTariffRead>(
      {url: `/api/v1/practices/${practiceId}/tariffs/effective`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Update Practice Tariff
 */
const updatePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdPut = (
    practiceId: string,
    tariffId: string,
    medicalPracticeTariffUpdate: MedicalPracticeTariffUpdate,
 options?: SecondParameter<typeof customInstance<MedicalPracticeTariffRead>>,) => {
      return customInstance<MedicalPracticeTariffRead>(
      {url: `/api/v1/practices/${practiceId}/tariffs/${tariffId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: medicalPracticeTariffUpdate
    },
      options);
    }
  /**
 * @summary Delete Practice Tariff
 */
const deletePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdDelete = (
    practiceId: string,
    tariffId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/practices/${practiceId}/tariffs/${tariffId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Prácticas indicadas en la internación, con el cargo que generó cada una.
 * @summary List Hospitalization Practices
 */
const listHospitalizationPracticesApiV1HospitalizationsHospitalizationIdPracticesGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead[]>>,) => {
      return customInstance<HospitalizationPracticeRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/practices`, method: 'GET'
    },
      options);
    }
  /**
 * Registra una práctica y el profesional que la indicó. Si se informa
 * ``performed_at`` queda como realizada y se carga a la cuenta de la internación.
 * @summary Register Hospitalization Practice
 */
const registerHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesPost = (
    hospitalizationId: string,
    hospitalizationPracticeCreate: HospitalizationPracticeCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/practices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticeCreate
    },
      options);
    }
  /**
 * La realización es la que genera el cargo, con el valor vigente de la práctica
 * para la cobertura de la internación.
 * @summary Perform Hospitalization Practice
 */
const performHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdPerformPost = (
    hospitalizationId: string,
    orderId: string,
    hospitalizationPracticePerformCreate: HospitalizationPracticePerformCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/practices/${orderId}/perform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticePerformCreate
    },
      options);
    }
  /**
 * Anula una práctica indicada y todavía no realizada.
 * @summary Cancel Hospitalization Practice
 */
const cancelHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdCancelPost = (
    hospitalizationId: string,
    orderId: string,
    hospitalizationPracticeCancelCreate: HospitalizationPracticeCancelCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/practices/${orderId}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticeCancelCreate
    },
      options);
    }
  return {listPracticesApiV1PracticesGet,createPracticeApiV1PracticesPost,getPracticeApiV1PracticesPracticeIdGet,updatePracticeApiV1PracticesPracticeIdPut,deletePracticeApiV1PracticesPracticeIdDelete,listPracticeTariffsApiV1PracticesPracticeIdTariffsGet,createPracticeTariffApiV1PracticesPracticeIdTariffsPost,getEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGet,updatePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdPut,deletePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdDelete,listHospitalizationPracticesApiV1HospitalizationsHospitalizationIdPracticesGet,registerHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesPost,performHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdPerformPost,cancelHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdCancelPost}};
export type ListPracticesApiV1PracticesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['listPracticesApiV1PracticesGet']>>>
export type CreatePracticeApiV1PracticesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['createPracticeApiV1PracticesPost']>>>
export type GetPracticeApiV1PracticesPracticeIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['getPracticeApiV1PracticesPracticeIdGet']>>>
export type UpdatePracticeApiV1PracticesPracticeIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['updatePracticeApiV1PracticesPracticeIdPut']>>>
export type DeletePracticeApiV1PracticesPracticeIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['deletePracticeApiV1PracticesPracticeIdDelete']>>>
export type ListPracticeTariffsApiV1PracticesPracticeIdTariffsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['listPracticeTariffsApiV1PracticesPracticeIdTariffsGet']>>>
export type CreatePracticeTariffApiV1PracticesPracticeIdTariffsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['createPracticeTariffApiV1PracticesPracticeIdTariffsPost']>>>
export type GetEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['getEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGet']>>>
export type UpdatePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['updatePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdPut']>>>
export type DeletePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['deletePracticeTariffApiV1PracticesPracticeIdTariffsTariffIdDelete']>>>
export type ListHospitalizationPracticesApiV1HospitalizationsHospitalizationIdPracticesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['listHospitalizationPracticesApiV1HospitalizationsHospitalizationIdPracticesGet']>>>
export type RegisterHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['registerHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesPost']>>>
export type PerformHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdPerformPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['performHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdPerformPost']>>>
export type CancelHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdCancelPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPractices>['cancelHospitalizationPracticeApiV1HospitalizationsHospitalizationIdPracticesOrderIdCancelPost']>>>
