/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  HealthPlanCreate,
  HealthPlanRead,
  PatientContactCreate,
  PatientContactRead,
  PatientCoverageCreate,
  PatientCoverageRead,
  PatientIdentifierCreate,
  PatientIdentifierRead,
  PatientMatchRead,
  PayerCreate,
  PayerRead,
  SearchPatientsApiV1PatientsSearchGetParams
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getRegistry = () => {
/**
 * Search identifiers before creating a patient, to reduce duplicates.
 * @summary Search Patients
 */
const searchPatientsApiV1PatientsSearchGet = (
    params: SearchPatientsApiV1PatientsSearchGetParams,
 options?: SecondParameter<typeof customInstance<PatientMatchRead[]>>,) => {
      return customInstance<PatientMatchRead[]>(
      {url: `/api/v1/patients/search`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary List Patient Identifiers
 */
const listPatientIdentifiersApiV1PatientsPatientIdIdentifiersGet = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<PatientIdentifierRead[]>>,) => {
      return customInstance<PatientIdentifierRead[]>(
      {url: `/api/v1/patients/${patientId}/identifiers`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient Identifier
 */
const createPatientIdentifierApiV1PatientsPatientIdIdentifiersPost = (
    patientId: string,
    patientIdentifierCreate: PatientIdentifierCreate,
 options?: SecondParameter<typeof customInstance<PatientIdentifierRead>>,) => {
      return customInstance<PatientIdentifierRead>(
      {url: `/api/v1/patients/${patientId}/identifiers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientIdentifierCreate
    },
      options);
    }
  /**
 * @summary List Patient Contacts
 */
const listPatientContactsApiV1PatientsPatientIdContactsGet = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<PatientContactRead[]>>,) => {
      return customInstance<PatientContactRead[]>(
      {url: `/api/v1/patients/${patientId}/contacts`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient Contact
 */
const createPatientContactApiV1PatientsPatientIdContactsPost = (
    patientId: string,
    patientContactCreate: PatientContactCreate,
 options?: SecondParameter<typeof customInstance<PatientContactRead>>,) => {
      return customInstance<PatientContactRead>(
      {url: `/api/v1/patients/${patientId}/contacts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientContactCreate
    },
      options);
    }
  /**
 * @summary List Payers
 */
const listPayersApiV1PayersGet = (

 options?: SecondParameter<typeof customInstance<PayerRead[]>>,) => {
      return customInstance<PayerRead[]>(
      {url: `/api/v1/payers`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Payer
 */
const createPayerApiV1PayersPost = (
    payerCreate: PayerCreate,
 options?: SecondParameter<typeof customInstance<PayerRead>>,) => {
      return customInstance<PayerRead>(
      {url: `/api/v1/payers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: payerCreate
    },
      options);
    }
  /**
 * @summary List Health Plans
 */
const listHealthPlansApiV1PayersPayerIdHealthPlansGet = (
    payerId: string,
 options?: SecondParameter<typeof customInstance<HealthPlanRead[]>>,) => {
      return customInstance<HealthPlanRead[]>(
      {url: `/api/v1/payers/${payerId}/health-plans`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Health Plan
 */
const createHealthPlanApiV1PayersPayerIdHealthPlansPost = (
    payerId: string,
    healthPlanCreate: HealthPlanCreate,
 options?: SecondParameter<typeof customInstance<HealthPlanRead>>,) => {
      return customInstance<HealthPlanRead>(
      {url: `/api/v1/payers/${payerId}/health-plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: healthPlanCreate
    },
      options);
    }
  /**
 * @summary List Patient Coverages
 */
const listPatientCoveragesApiV1PatientsPatientIdCoveragesGet = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<PatientCoverageRead[]>>,) => {
      return customInstance<PatientCoverageRead[]>(
      {url: `/api/v1/patients/${patientId}/coverages`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient Coverage
 */
const createPatientCoverageApiV1PatientsPatientIdCoveragesPost = (
    patientId: string,
    patientCoverageCreate: PatientCoverageCreate,
 options?: SecondParameter<typeof customInstance<PatientCoverageRead>>,) => {
      return customInstance<PatientCoverageRead>(
      {url: `/api/v1/patients/${patientId}/coverages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientCoverageCreate
    },
      options);
    }
  return {searchPatientsApiV1PatientsSearchGet,listPatientIdentifiersApiV1PatientsPatientIdIdentifiersGet,createPatientIdentifierApiV1PatientsPatientIdIdentifiersPost,listPatientContactsApiV1PatientsPatientIdContactsGet,createPatientContactApiV1PatientsPatientIdContactsPost,listPayersApiV1PayersGet,createPayerApiV1PayersPost,listHealthPlansApiV1PayersPayerIdHealthPlansGet,createHealthPlanApiV1PayersPayerIdHealthPlansPost,listPatientCoveragesApiV1PatientsPatientIdCoveragesGet,createPatientCoverageApiV1PatientsPatientIdCoveragesPost}};
export type SearchPatientsApiV1PatientsSearchGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['searchPatientsApiV1PatientsSearchGet']>>>
export type ListPatientIdentifiersApiV1PatientsPatientIdIdentifiersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['listPatientIdentifiersApiV1PatientsPatientIdIdentifiersGet']>>>
export type CreatePatientIdentifierApiV1PatientsPatientIdIdentifiersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['createPatientIdentifierApiV1PatientsPatientIdIdentifiersPost']>>>
export type ListPatientContactsApiV1PatientsPatientIdContactsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['listPatientContactsApiV1PatientsPatientIdContactsGet']>>>
export type CreatePatientContactApiV1PatientsPatientIdContactsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['createPatientContactApiV1PatientsPatientIdContactsPost']>>>
export type ListPayersApiV1PayersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['listPayersApiV1PayersGet']>>>
export type CreatePayerApiV1PayersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['createPayerApiV1PayersPost']>>>
export type ListHealthPlansApiV1PayersPayerIdHealthPlansGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['listHealthPlansApiV1PayersPayerIdHealthPlansGet']>>>
export type CreateHealthPlanApiV1PayersPayerIdHealthPlansPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['createHealthPlanApiV1PayersPayerIdHealthPlansPost']>>>
export type ListPatientCoveragesApiV1PatientsPatientIdCoveragesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['listPatientCoveragesApiV1PatientsPatientIdCoveragesGet']>>>
export type CreatePatientCoverageApiV1PatientsPatientIdCoveragesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getRegistry>['createPatientCoverageApiV1PatientsPatientIdCoveragesPost']>>>
