/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  CurrentUserRead,
  LoginRequest,
  SessionRead,
  UserCreate,
  UserRead,
  UserUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuth = () => {
/**
 * Devuelve el token de la sesión y lo que el usuario puede hacer.
 * @summary Login
 */
const loginApiV1AuthLoginPost = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance<SessionRead>>,) => {
      return customInstance<SessionRead>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      options);
    }
  /**
 * @summary Logout
 */
const logoutApiV1AuthLogoutPost = (

 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/auth/logout`, method: 'POST'
    },
      options);
    }
  /**
 * @summary Me
 */
const meApiV1AuthMeGet = (

 options?: SecondParameter<typeof customInstance<CurrentUserRead>>,) => {
      return customInstance<CurrentUserRead>(
      {url: `/api/v1/auth/me`, method: 'GET'
    },
      options);
    }
  /**
 * @summary List Users
 */
const listUsersApiV1UsersGet = (

 options?: SecondParameter<typeof customInstance<UserRead[]>>,) => {
      return customInstance<UserRead[]>(
      {url: `/api/v1/users`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create User
 */
const createUserApiV1UsersPost = (
    userCreate: UserCreate,
 options?: SecondParameter<typeof customInstance<UserRead>>,) => {
      return customInstance<UserRead>(
      {url: `/api/v1/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userCreate
    },
      options);
    }
  /**
 * Cambiar el rol, dar de baja o cambiar la contraseña cierra las sesiones abiertas.
 * @summary Update User
 */
const updateUserApiV1UsersUserIdPut = (
    userId: string,
    userUpdate: UserUpdate,
 options?: SecondParameter<typeof customInstance<UserRead>>,) => {
      return customInstance<UserRead>(
      {url: `/api/v1/users/${userId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userUpdate
    },
      options);
    }
  return {loginApiV1AuthLoginPost,logoutApiV1AuthLogoutPost,meApiV1AuthMeGet,listUsersApiV1UsersGet,createUserApiV1UsersPost,updateUserApiV1UsersUserIdPut}};
export type LoginApiV1AuthLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['loginApiV1AuthLoginPost']>>>
export type LogoutApiV1AuthLogoutPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['logoutApiV1AuthLogoutPost']>>>
export type MeApiV1AuthMeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['meApiV1AuthMeGet']>>>
export type ListUsersApiV1UsersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['listUsersApiV1UsersGet']>>>
export type CreateUserApiV1UsersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['createUserApiV1UsersPost']>>>
export type UpdateUserApiV1UsersUserIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['updateUserApiV1UsersUserIdPut']>>>
