/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  DischargePrescriptionCreate,
  DischargePrescriptionRead,
  DischargePrescriptionUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getPrescriptions = () => {
/**
 * Lo que el paciente se lleva indicado: medicación y prácticas.
 * @summary List Discharge Prescriptions
 */
const listDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<DischargePrescriptionRead[]>>,) => {
      return customInstance<DischargePrescriptionRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-prescriptions`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Add Discharge Prescription
 */
const addDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPost = (
    hospitalizationId: string,
    dischargePrescriptionCreate: DischargePrescriptionCreate,
 options?: SecondParameter<typeof customInstance<DischargePrescriptionRead>>,) => {
      return customInstance<DischargePrescriptionRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-prescriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dischargePrescriptionCreate
    },
      options);
    }
  /**
 * @summary Update Discharge Prescription
 */
const updateDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdPut = (
    hospitalizationId: string,
    prescriptionId: string,
    dischargePrescriptionUpdate: DischargePrescriptionUpdate,
 options?: SecondParameter<typeof customInstance<DischargePrescriptionRead>>,) => {
      return customInstance<DischargePrescriptionRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-prescriptions/${prescriptionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: dischargePrescriptionUpdate
    },
      options);
    }
  /**
 * @summary Remove Discharge Prescription
 */
const removeDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdDelete = (
    hospitalizationId: string,
    prescriptionId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-prescriptions/${prescriptionId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Receta e indicación de prácticas en un PDF, una hoja cada una.
 * @summary Print Discharge Prescriptions
 */
const printDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPdfGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<Blob>>,) => {
      return customInstance<Blob>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-prescriptions/pdf`, method: 'GET',
        responseType: 'blob'
    },
      options);
    }
  return {listDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsGet,addDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPost,updateDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdPut,removeDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdDelete,printDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPdfGet}};
export type ListDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPrescriptions>['listDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsGet']>>>
export type AddDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPrescriptions>['addDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPost']>>>
export type UpdateDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPrescriptions>['updateDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdPut']>>>
export type RemoveDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPrescriptions>['removeDischargePrescriptionApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPrescriptionIdDelete']>>>
export type PrintDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPdfGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPrescriptions>['printDischargePrescriptionsApiV1HospitalizationsHospitalizationIdDischargePrescriptionsPdfGet']>>>
