/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  BedOperationCreate,
  BedRead,
  BedReservationCancelCreate,
  BedReservationCreate,
  BedReservationRead,
  BedStatusHistoryRead,
  SearchAvailableBedsApiV1BedsAvailableGetParams
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getBedWorkflow = () => {
/**
 * Compatible beds for an admission: available, unreserved and unoccupied.
 * @summary Search Available Beds
 */
const searchAvailableBedsApiV1BedsAvailableGet = (
    params?: SearchAvailableBedsApiV1BedsAvailableGetParams,
 options?: SecondParameter<typeof customInstance<BedRead[]>>,) => {
      return customInstance<BedRead[]>(
      {url: `/api/v1/beds/available`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Bed Status History
 */
const bedStatusHistoryApiV1BedsBedIdStatusHistoryGet = (
    bedId: string,
 options?: SecondParameter<typeof customInstance<BedStatusHistoryRead[]>>,) => {
      return customInstance<BedStatusHistoryRead[]>(
      {url: `/api/v1/beds/${bedId}/status-history`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Start Bed Cleaning
 */
const startBedCleaningApiV1BedsBedIdCleaningStartPost = (
    bedId: string,
    bedOperationCreate: BedOperationCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}/cleaning/start`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedOperationCreate
    },
      options);
    }
  /**
 * @summary Complete Bed Cleaning
 */
const completeBedCleaningApiV1BedsBedIdCleaningCompletePost = (
    bedId: string,
    bedOperationCreate: BedOperationCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}/cleaning/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedOperationCreate
    },
      options);
    }
  /**
 * @summary List Bed Reservations
 */
const listBedReservationsApiV1HospitalizationsHospitalizationIdBedReservationsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<BedReservationRead[]>>,) => {
      return customInstance<BedReservationRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/bed-reservations`, method: 'GET'
    },
      options);
    }
  /**
 * Hold an available bed. The reservation expires so abandoned flows free the bed.
 * @summary Reserve Bed
 */
const reserveBedApiV1HospitalizationsHospitalizationIdBedReservationsPost = (
    hospitalizationId: string,
    bedReservationCreate: BedReservationCreate,
 options?: SecondParameter<typeof customInstance<BedReservationRead>>,) => {
      return customInstance<BedReservationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/bed-reservations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedReservationCreate
    },
      options);
    }
  /**
 * @summary Cancel Bed Reservation
 */
const cancelBedReservationApiV1BedReservationsReservationIdCancelPost = (
    reservationId: string,
    bedReservationCancelCreate: BedReservationCancelCreate,
 options?: SecondParameter<typeof customInstance<BedReservationRead>>,) => {
      return customInstance<BedReservationRead>(
      {url: `/api/v1/bed-reservations/${reservationId}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedReservationCancelCreate
    },
      options);
    }
  /**
 * Release beds whose reservation expired; intended for a scheduled job.
 * @summary Expire Due Bed Reservations
 */
const expireDueBedReservationsApiV1BedReservationsExpireDuePost = (

 options?: SecondParameter<typeof customInstance<BedReservationRead[]>>,) => {
      return customInstance<BedReservationRead[]>(
      {url: `/api/v1/bed-reservations/expire-due`, method: 'POST'
    },
      options);
    }
  return {searchAvailableBedsApiV1BedsAvailableGet,bedStatusHistoryApiV1BedsBedIdStatusHistoryGet,startBedCleaningApiV1BedsBedIdCleaningStartPost,completeBedCleaningApiV1BedsBedIdCleaningCompletePost,listBedReservationsApiV1HospitalizationsHospitalizationIdBedReservationsGet,reserveBedApiV1HospitalizationsHospitalizationIdBedReservationsPost,cancelBedReservationApiV1BedReservationsReservationIdCancelPost,expireDueBedReservationsApiV1BedReservationsExpireDuePost}};
export type SearchAvailableBedsApiV1BedsAvailableGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['searchAvailableBedsApiV1BedsAvailableGet']>>>
export type BedStatusHistoryApiV1BedsBedIdStatusHistoryGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['bedStatusHistoryApiV1BedsBedIdStatusHistoryGet']>>>
export type StartBedCleaningApiV1BedsBedIdCleaningStartPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['startBedCleaningApiV1BedsBedIdCleaningStartPost']>>>
export type CompleteBedCleaningApiV1BedsBedIdCleaningCompletePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['completeBedCleaningApiV1BedsBedIdCleaningCompletePost']>>>
export type ListBedReservationsApiV1HospitalizationsHospitalizationIdBedReservationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['listBedReservationsApiV1HospitalizationsHospitalizationIdBedReservationsGet']>>>
export type ReserveBedApiV1HospitalizationsHospitalizationIdBedReservationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['reserveBedApiV1HospitalizationsHospitalizationIdBedReservationsPost']>>>
export type CancelBedReservationApiV1BedReservationsReservationIdCancelPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['cancelBedReservationApiV1BedReservationsReservationIdCancelPost']>>>
export type ExpireDueBedReservationsApiV1BedReservationsExpireDuePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBedWorkflow>['expireDueBedReservationsApiV1BedReservationsExpireDuePost']>>>
