/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AccountCloseCreate,
  AccountRead,
  AdministrativeDischargeCreate,
  CareTeamMemberCreate,
  CareTeamMemberRead,
  CareTeamRead,
  ChargeItemCreate,
  ChargeItemRead,
  ChargeItemVoidCreate,
  ClinicalDischargeCreate,
  DischargePlanCreate,
  DischargePlanRead,
  DischargeRead,
  HospitalizationEventRead,
  HospitalizationRead,
  PhysicalDepartureCreate,
  ServiceAssignmentCreate,
  ServiceAssignmentRead
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getHospitalizationWorkflow = () => {
/**
 * @summary Get Hospitalization
 */
const getHospitalizationApiV1HospitalizationsHospitalizationIdGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<HospitalizationRead>>,) => {
      return customInstance<HospitalizationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary List Service Assignments
 */
const listServiceAssignmentsApiV1HospitalizationsHospitalizationIdServiceAssignmentsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<ServiceAssignmentRead[]>>,) => {
      return customInstance<ServiceAssignmentRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/service-assignments`, method: 'GET'
    },
      options);
    }
  /**
 * Change the responsible service keeping the previous assignment as history.
 * @summary Assign Service
 */
const assignServiceApiV1HospitalizationsHospitalizationIdServiceAssignmentsPost = (
    hospitalizationId: string,
    serviceAssignmentCreate: ServiceAssignmentCreate,
 options?: SecondParameter<typeof customInstance<ServiceAssignmentRead>>,) => {
      return customInstance<ServiceAssignmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/service-assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: serviceAssignmentCreate
    },
      options);
    }
  /**
 * @summary Get Care Team
 */
const getCareTeamApiV1HospitalizationsHospitalizationIdCareTeamGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<CareTeamRead>>,) => {
      return customInstance<CareTeamRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/care-team`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Add Care Team Member
 */
const addCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersPost = (
    hospitalizationId: string,
    careTeamMemberCreate: CareTeamMemberCreate,
 options?: SecondParameter<typeof customInstance<CareTeamMemberRead>>,) => {
      return customInstance<CareTeamMemberRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/care-team/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: careTeamMemberCreate
    },
      options);
    }
  /**
 * End a participation. Membership history is closed, never deleted.
 * @summary End Care Team Member
 */
const endCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersMemberIdEndPost = (
    hospitalizationId: string,
    memberId: string,
 options?: SecondParameter<typeof customInstance<CareTeamMemberRead>>,) => {
      return customInstance<CareTeamMemberRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/care-team/members/${memberId}/end`, method: 'POST'
    },
      options);
    }
  /**
 * @summary List Discharge Plans
 */
const listDischargePlansApiV1HospitalizationsHospitalizationIdDischargePlansGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<DischargePlanRead[]>>,) => {
      return customInstance<DischargePlanRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-plans`, method: 'GET'
    },
      options);
    }
  /**
 * Plan the discharge. The bed stays occupied and the hospitalization active.
 * @summary Plan Discharge
 */
const planDischargeApiV1HospitalizationsHospitalizationIdDischargePlansPost = (
    hospitalizationId: string,
    dischargePlanCreate: DischargePlanCreate,
 options?: SecondParameter<typeof customInstance<DischargePlanRead>>,) => {
      return customInstance<DischargePlanRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge-plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dischargePlanCreate
    },
      options);
    }
  /**
 * @summary Get Discharge
 */
const getDischargeApiV1HospitalizationsHospitalizationIdDischargeGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<DischargeRead>>,) => {
      return customInstance<DischargeRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/discharge`, method: 'GET'
    },
      options);
    }
  /**
 * Clinical discharge. The bed remains OCCUPIED until the patient physically leaves.
 * @summary Clinical Discharge
 */
const clinicalDischargeApiV1HospitalizationsHospitalizationIdClinicalDischargePost = (
    hospitalizationId: string,
    clinicalDischargeCreate: ClinicalDischargeCreate,
 options?: SecondParameter<typeof customInstance<DischargeRead>>,) => {
      return customInstance<DischargeRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/clinical-discharge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clinicalDischargeCreate
    },
      options);
    }
  /**
 * The patient leaves the bed: the assignment ends and the bed goes to cleaning.
 * @summary Physical Departure
 */
const physicalDepartureApiV1HospitalizationsHospitalizationIdPhysicalDeparturePost = (
    hospitalizationId: string,
    physicalDepartureCreate: PhysicalDepartureCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationRead>>,) => {
      return customInstance<HospitalizationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/physical-departure`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: physicalDepartureCreate
    },
      options);
    }
  /**
 * Administrative discharge. Billing continues on its own afterwards.
 * @summary Administrative Discharge
 */
const administrativeDischargeApiV1HospitalizationsHospitalizationIdAdministrativeDischargePost = (
    hospitalizationId: string,
    administrativeDischargeCreate: AdministrativeDischargeCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationRead>>,) => {
      return customInstance<HospitalizationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/administrative-discharge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: administrativeDischargeCreate
    },
      options);
    }
  /**
 * @summary List Hospitalization Events
 */
const listHospitalizationEventsApiV1HospitalizationsHospitalizationIdEventsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<HospitalizationEventRead[]>>,) => {
      return customInstance<HospitalizationEventRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/events`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get Account
 */
const getAccountApiV1HospitalizationsHospitalizationIdAccountGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<AccountRead>>,) => {
      return customInstance<AccountRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/account`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Add Charge Item
 */
const addChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsPost = (
    hospitalizationId: string,
    chargeItemCreate: ChargeItemCreate,
 options?: SecondParameter<typeof customInstance<ChargeItemRead>>,) => {
      return customInstance<ChargeItemRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/account/charge-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chargeItemCreate
    },
      options);
    }
  /**
 * Anula un cargo de la cuenta. El cargo queda registrado y deja de sumar al total.
 * @summary Void Charge Item
 */
const voidChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsChargeItemIdVoidPost = (
    hospitalizationId: string,
    chargeItemId: string,
    chargeItemVoidCreate: ChargeItemVoidCreate,
 options?: SecondParameter<typeof customInstance<ChargeItemRead>>,) => {
      return customInstance<ChargeItemRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/account/charge-items/${chargeItemId}/void`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chargeItemVoidCreate
    },
      options);
    }
  /**
 * Financial closure: closes the account and the hospitalization.
 * @summary Close Account
 */
const closeAccountApiV1AccountsAccountIdClosePost = (
    accountId: string,
    accountCloseCreate: AccountCloseCreate,
 options?: SecondParameter<typeof customInstance<AccountRead>>,) => {
      return customInstance<AccountRead>(
      {url: `/api/v1/accounts/${accountId}/close`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountCloseCreate
    },
      options);
    }
  return {getHospitalizationApiV1HospitalizationsHospitalizationIdGet,listServiceAssignmentsApiV1HospitalizationsHospitalizationIdServiceAssignmentsGet,assignServiceApiV1HospitalizationsHospitalizationIdServiceAssignmentsPost,getCareTeamApiV1HospitalizationsHospitalizationIdCareTeamGet,addCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersPost,endCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersMemberIdEndPost,listDischargePlansApiV1HospitalizationsHospitalizationIdDischargePlansGet,planDischargeApiV1HospitalizationsHospitalizationIdDischargePlansPost,getDischargeApiV1HospitalizationsHospitalizationIdDischargeGet,clinicalDischargeApiV1HospitalizationsHospitalizationIdClinicalDischargePost,physicalDepartureApiV1HospitalizationsHospitalizationIdPhysicalDeparturePost,administrativeDischargeApiV1HospitalizationsHospitalizationIdAdministrativeDischargePost,listHospitalizationEventsApiV1HospitalizationsHospitalizationIdEventsGet,getAccountApiV1HospitalizationsHospitalizationIdAccountGet,addChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsPost,voidChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsChargeItemIdVoidPost,closeAccountApiV1AccountsAccountIdClosePost}};
export type GetHospitalizationApiV1HospitalizationsHospitalizationIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['getHospitalizationApiV1HospitalizationsHospitalizationIdGet']>>>
export type ListServiceAssignmentsApiV1HospitalizationsHospitalizationIdServiceAssignmentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['listServiceAssignmentsApiV1HospitalizationsHospitalizationIdServiceAssignmentsGet']>>>
export type AssignServiceApiV1HospitalizationsHospitalizationIdServiceAssignmentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['assignServiceApiV1HospitalizationsHospitalizationIdServiceAssignmentsPost']>>>
export type GetCareTeamApiV1HospitalizationsHospitalizationIdCareTeamGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['getCareTeamApiV1HospitalizationsHospitalizationIdCareTeamGet']>>>
export type AddCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['addCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersPost']>>>
export type EndCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersMemberIdEndPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['endCareTeamMemberApiV1HospitalizationsHospitalizationIdCareTeamMembersMemberIdEndPost']>>>
export type ListDischargePlansApiV1HospitalizationsHospitalizationIdDischargePlansGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['listDischargePlansApiV1HospitalizationsHospitalizationIdDischargePlansGet']>>>
export type PlanDischargeApiV1HospitalizationsHospitalizationIdDischargePlansPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['planDischargeApiV1HospitalizationsHospitalizationIdDischargePlansPost']>>>
export type GetDischargeApiV1HospitalizationsHospitalizationIdDischargeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['getDischargeApiV1HospitalizationsHospitalizationIdDischargeGet']>>>
export type ClinicalDischargeApiV1HospitalizationsHospitalizationIdClinicalDischargePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['clinicalDischargeApiV1HospitalizationsHospitalizationIdClinicalDischargePost']>>>
export type PhysicalDepartureApiV1HospitalizationsHospitalizationIdPhysicalDeparturePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['physicalDepartureApiV1HospitalizationsHospitalizationIdPhysicalDeparturePost']>>>
export type AdministrativeDischargeApiV1HospitalizationsHospitalizationIdAdministrativeDischargePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['administrativeDischargeApiV1HospitalizationsHospitalizationIdAdministrativeDischargePost']>>>
export type ListHospitalizationEventsApiV1HospitalizationsHospitalizationIdEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['listHospitalizationEventsApiV1HospitalizationsHospitalizationIdEventsGet']>>>
export type GetAccountApiV1HospitalizationsHospitalizationIdAccountGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['getAccountApiV1HospitalizationsHospitalizationIdAccountGet']>>>
export type AddChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['addChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsPost']>>>
export type VoidChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsChargeItemIdVoidPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['voidChargeItemApiV1HospitalizationsHospitalizationIdAccountChargeItemsChargeItemIdVoidPost']>>>
export type CloseAccountApiV1AccountsAccountIdClosePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getHospitalizationWorkflow>['closeAccountApiV1AccountsAccountIdClosePost']>>>
