/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AccountStatus } from './accountStatus';
import type { ChargeItemRead } from './chargeItemRead';

export interface AccountRead {
  id: string;
  hospitalization_id: string;
  patient_id: string;
  coverage_id: string | null;
  status: AccountStatus;
  currency: string;
  opened_at: string;
  ready_for_review_at: string | null;
  closed_at: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  total_amount?: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  voided_amount?: string;
  charge_items?: ChargeItemRead[];
}
