/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type AccountStatus = typeof AccountStatus[keyof typeof AccountStatus];


export const AccountStatus = {
  OPEN: 'OPEN',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;
