/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AdministrationStatus } from './administrationStatus';
import type { MedicationRoute } from './medicationRoute';

export interface AdministrationRead {
  id: string;
  treatment_id: string;
  hospitalization_id: string;
  status: AdministrationStatus;
  administered_at: string;
  dose: string | null;
  route: MedicationRoute | null;
  omission_reason: string | null;
  administered_by_id: string | null;
  recorded_by_user_id: string | null;
  recorded_by_user_name: string | null;
  notes: string | null;
  voided_at: string | null;
  voided_by: string | null;
  void_reason: string | null;
  created_at: string;
}
