/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Por qué no se va a internar: el paciente no vino, se reprogramó, desistió…
 */
export interface AdmissionCancelCreate {
  /**
     * @minLength 3
     * @maxLength 500
     */
  reason: string;
  cancelled_by?: string | null;
}
