/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type AdmissionType = typeof AdmissionType[keyof typeof AdmissionType];


export const AdmissionType = {
  PRE_ADMISSION: 'PRE_ADMISSION',
  SCHEDULED: 'SCHEDULED',
  EMERGENCY: 'EMERGENCY',
} as const;
