/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ConsentType } from './consentType';

export interface AdmissionConsentCreate {
  consent_type: ConsentType;
  /**
     * @minLength 1
     * @maxLength 150
     */
  signed_by: string;
  signed_at?: string | null;
  notes?: string | null;
}
