/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AdmissionConsentCreate } from './admissionConsentCreate';
import type { AdmissionOrigin } from './admissionOrigin';
import type { AdmissionType } from './admissionType';
import type { AuthorizationStatus } from './authorizationStatus';
import type { HospitalizationDiagnosisCreate } from './hospitalizationDiagnosisCreate';
import type { PatientCoverageCreate } from './patientCoverageCreate';

export interface AdmissionCreate {
  patient_id: string;
  origin: AdmissionOrigin;
  admission_type: AdmissionType;
  facility_id?: string | null;
  identity_validated?: boolean;
  duplicate_checked?: boolean;
  coverage_id?: string | null;
  coverage?: PatientCoverageCreate | null;
  authorization_status?: AuthorizationStatus;
  authorization_number?: string | null;
  /**
     * @minLength 1
     * @maxLength 150
     */
  responsible_contact_name: string;
  /**
     * @minLength 1
     * @maxLength 80
     */
  responsible_contact_phone: string;
  responsible_contact_relationship?: string | null;
  /**
     * @minLength 3
     * @maxLength 500
     */
  admission_reason: string;
  /**
     * @minLength 1
     * @maxLength 150
     */
  responsible_physician: string;
  responsible_physician_id?: string | null;
  requesting_service_id?: string | null;
  presumptive_diagnosis?: string | null;
  /** @maxItems 20 */
  diagnoses?: HospitalizationDiagnosisCreate[];
  requested_bed_id?: string | null;
  consents?: AdmissionConsentCreate[];
  notes?: string | null;
  confirm_admission?: boolean;
}
