export type AdmissionOrigin = typeof AdmissionOrigin[keyof typeof AdmissionOrigin];

export const AdmissionOrigin = {
  EMERGENCY_ROOM: 'EMERGENCY_ROOM',
  OUTPATIENT_CLINIC: 'OUTPATIENT_CLINIC',
  SCHEDULED_SURGERY: 'SCHEDULED_SURGERY',
  EXTERNAL_REFERRAL: 'EXTERNAL_REFERRAL',
  HOME_HOSPITALIZATION: 'HOME_HOSPITALIZATION',
  SPECIAL_CARE_UNIT: 'SPECIAL_CARE_UNIT',
  SCHEDULED_MEDICAL_ORDER: 'SCHEDULED_MEDICAL_ORDER',
} as const;
