/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AdmissionConsentCreate } from './admissionConsentCreate';

/**
 * Contacto y consentimientos que se toman cuando el paciente llega a internarse.
 */
export interface AdmissionArrivalCreate {
  responsible_contact_name?: string | null;
  responsible_contact_phone?: string | null;
  responsible_contact_relationship?: string | null;
  consents?: AdmissionConsentCreate[];
}
