/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ConsentType } from './consentType';

export interface AdmissionConsentRead {
  id: string;
  admission_id: string;
  consent_type: ConsentType;
  signed_by: string;
  signed_at: string | null;
  notes: string | null;
  created_at: string;
}
