/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AdministrationStatus } from './administrationStatus';

/**
 * Una toma: lo que se le dio al paciente, o lo que no se le pudo dar.
 */
export interface AdministrationCreate {
  status?: AdministrationStatus;
  administered_at?: string | null;
  dose?: string | null;
  omission_reason?: string | null;
  administered_by_id?: string | null;
  notes?: string | null;
}
