/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorizationState } from './authorizationState';
import type { AuthorizationType } from './authorizationType';

export interface AuthorizationRead {
  id: string;
  patient_id: string;
  admission_id: string | null;
  hospitalization_id: string | null;
  patient_coverage_id: string | null;
  authorization_type: AuthorizationType;
  authorization_number: string | null;
  status: AuthorizationState;
  requested_at: string;
  requested_by: string | null;
  resolved_at: string | null;
  authorized_at: string | null;
  valid_from: string | null;
  valid_until: string | null;
  notes: string | null;
  created_at: string;
}
