/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorizationType } from './authorizationType';

export interface AuthorizationRequestCreate {
  authorization_type?: AuthorizationType;
  patient_coverage_id?: string | null;
  authorization_number?: string | null;
  requested_by?: string | null;
  valid_from?: string | null;
  valid_until?: string | null;
  notes?: string | null;
}
