/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary of the authorization requirement of an admission request.
 */
export type AuthorizationStatus = typeof AuthorizationStatus[keyof typeof AuthorizationStatus];


export const AuthorizationStatus = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  REJECTED: 'REJECTED',
} as const;
