/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthorizationState } from './authorizationState';

export interface AuthorizationResolveCreate {
  status: AuthorizationState;
  authorization_number?: string | null;
  valid_from?: string | null;
  valid_until?: string | null;
  notes?: string | null;
}
