/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { BedStatus } from './bedStatus';

export interface BedAssignmentRead {
  id: string;
  hospitalization_id: string | null;
  bed_id: string;
  status: BedStatus;
  started_at: string;
  ended_at: string | null;
  assignment_reason?: string | null;
  assigned_by?: string | null;
  ended_by?: string | null;
}
