/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface BedReservationCreate {
  bed_id: string;
  expires_in_minutes?: number | null;
  reserved_by?: string | null;
  reason?: string | null;
}
