/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { BedStatus } from './bedStatus';
import type { PatientRead } from './patientRead';

export interface BedRead {
  id: string;
  facility_id: string;
  room_id: string;
  code: string;
  ward: string;
  room: string;
  status: BedStatus;
  patient?: PatientRead | null;
}
