/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { BedStatus } from './bedStatus';

export interface BedStatusHistoryRead {
  id: string;
  bed_id: string;
  previous_status: BedStatus | null;
  new_status: BedStatus;
  changed_at: string;
  changed_by: string | null;
  reason: string | null;
}
