/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface BedTransferCreate {
  destination_bed_id: string;
  reason?: string | null;
  requested_by?: string | null;
  completed_by?: string | null;
}
