/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { TransferStatus } from './transferStatus';

export interface BedTransferRead {
  id: string;
  hospitalization_id: string;
  from_bed_id: string;
  to_bed_id: string;
  status: TransferStatus;
  requested_at: string;
  completed_at: string | null;
  cancelled_at: string | null;
  reason: string | null;
}
