/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { CareTeamRole } from './careTeamRole';

export interface CareTeamMemberCreate {
  practitioner_id: string;
  role: CareTeamRole;
  notes?: string | null;
}
