/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { CareTeamRole } from './careTeamRole';

export interface CareTeamMemberRead {
  id: string;
  care_team_id: string;
  practitioner_id: string;
  role: CareTeamRole;
  started_at: string;
  ended_at: string | null;
  notes: string | null;
}
