/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { CareTeamMemberRead } from './careTeamMemberRead';

export interface CareTeamRead {
  id: string;
  hospitalization_id: string;
  members?: CareTeamMemberRead[];
}
