/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ChargeCategory } from './chargeCategory';
import type { ChargeItemStatus } from './chargeItemStatus';
import type { ResponsibleParty } from './responsibleParty';

export interface ChargeItemRead {
  id: string;
  account_id: string;
  practice_id?: string | null;
  practice_code?: string | null;
  category: ChargeCategory;
  responsible_party: ResponsibleParty;
  description: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  quantity: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  unit_price: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount: string;
  charged_at: string;
  recorded_by: string | null;
  notes: string | null;
  status?: ChargeItemStatus;
  voided_at?: string | null;
  voided_by?: string | null;
  void_reason?: string | null;
}
