/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A wrong charge is voided, never deleted: the line stays in the account.
 */
export interface ChargeItemVoidCreate {
  reason?: string | null;
  actor?: string | null;
}
