/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ChargeCategory } from './chargeCategory';
import type { ResponsibleParty } from './responsibleParty';

export interface ChargeItemCreate {
  practice_id?: string | null;
  category: ChargeCategory;
  responsible_party?: ResponsibleParty | null;
  /**
     * @minLength 1
     * @maxLength 250
     */
  description: string;
  quantity?: number | string;
  unit_price: number | string;
  charged_at?: string | null;
  recorded_by?: string | null;
  notes?: string | null;
}
