/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ChargeItemStatus = typeof ChargeItemStatus[keyof typeof ChargeItemStatus];


export const ChargeItemStatus = {
  ACTIVE: 'ACTIVE',
  VOID: 'VOID',
} as const;
