/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type CheckPracticeCoverageApiV1HospitalizationsHospitalizationIdPracticesCoverageCheckGetParams = {
practice_id: string;
on?: string | null;
};
