/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ClinicalNoteStatus = typeof ClinicalNoteStatus[keyof typeof ClinicalNoteStatus];


export const ClinicalNoteStatus = {
  ACTIVE: 'ACTIVE',
  VOID: 'VOID',
} as const;
