/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DischargeDestination } from './dischargeDestination';
import type { DischargeType } from './dischargeType';

export interface ClinicalDischargeCreate {
  discharge_type?: DischargeType;
  discharge_reason?: string | null;
  destination?: DischargeDestination | null;
  ordered_by?: string | null;
  ordered_by_practitioner_id?: string | null;
  effective_at?: string | null;
  instructions?: string | null;
}
