/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Una nota cargada por error se anula con su motivo; no se borra.
 */
export interface ClinicalNoteVoidCreate {
  reason?: string | null;
  actor?: string | null;
}
