/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ClinicalNoteKind } from './clinicalNoteKind';
import type { ClinicalNoteStatus } from './clinicalNoteStatus';

export interface ClinicalNoteRead {
  id: string;
  hospitalization_id: string;
  kind: ClinicalNoteKind;
  status: ClinicalNoteStatus;
  note: string;
  author_id: string | null;
  service_id: string | null;
  recorded_by_user_id: string | null;
  recorded_by_user_name: string | null;
  noted_at: string;
  voided_at: string | null;
  voided_by: string | null;
  void_reason: string | null;
  created_at: string;
}
