/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ClinicalNoteKind } from './clinicalNoteKind';

/**
 * Una evolución, una observación o la atención de otro médico.
 */
export interface ClinicalNoteCreate {
  kind?: ClinicalNoteKind;
  /** @minLength 1 */
  note: string;
  author_id?: string | null;
  service_id?: string | null;
  noted_at?: string | null;
}
