/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ConsentType = typeof ConsentType[keyof typeof ConsentType];


export const ConsentType = {
  GENERAL_ADMISSION: 'GENERAL_ADMISSION',
  DATA_PROCESSING: 'DATA_PROCESSING',
  PROCEDURE: 'PROCEDURE',
  ANESTHESIA: 'ANESTHESIA',
  TRANSFER: 'TRANSFER',
} as const;
