/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission';
import type { UserRead } from './userRead';

export interface CurrentUserRead {
  user: UserRead;
  permissions: Permission[];
}
