/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisLevel } from './diagnosisLevel';

export interface DiagnosisCodeRead {
  id: string;
  code: string;
  description: string;
  level: DiagnosisLevel;
  parent_code: string | null;
  chapter_code: string | null;
  is_active: boolean;
  notes: string | null;
  created_at: string;
  child_count?: number;
  /** Si se le puede asentar a un paciente: capítulos y grupos solo agrupan. */
  readonly codifiable: boolean;
}
