/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type DischargePlanStatus = typeof DischargePlanStatus[keyof typeof DischargePlanStatus];


export const DischargePlanStatus = {
  PLANNED: 'PLANNED',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
