/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PrescriptionKind } from './prescriptionKind';

/**
 * Un renglón de la receta o de las indicaciones.
 *
 * ``practice_id`` solo tiene sentido en las indicaciones de prácticas: trae el nombre del
 * nomenclador. La medicación va como texto, porque el vademécum no vive en este sistema.
 */
export interface DischargePrescriptionCreate {
  kind: PrescriptionKind;
  practice_id?: string | null;
  /** @maxLength 250 */
  description?: string;
  presentation?: string | null;
  dosage?: string | null;
  quantity?: number | string;
  duration_days?: number | null;
  instructions?: string | null;
  prescribed_by_id?: string | null;
}
