/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PrescriptionKind } from './prescriptionKind';

export interface DischargePrescriptionUpdate {
  kind: PrescriptionKind;
  practice_id?: string | null;
  /** @maxLength 250 */
  description?: string;
  presentation?: string | null;
  dosage?: string | null;
  quantity?: number | string;
  duration_days?: number | null;
  instructions?: string | null;
  prescribed_by_id?: string | null;
}
