/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PrescriptionKind } from './prescriptionKind';

export interface DischargePrescriptionRead {
  id: string;
  hospitalization_id: string;
  kind: PrescriptionKind;
  practice_id: string | null;
  description: string;
  presentation: string | null;
  dosage: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  quantity: string;
  duration_days: number | null;
  instructions: string | null;
  prescribed_by_id: string | null;
  prescribed_by_user_name: string | null;
  prescribed_at: string;
  created_at: string;
}
