/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DoseState } from './doseState';

export interface DoseSlotRead {
  due_at: string;
  state: DoseState;
  administration_id: string | null;
  dose: string | null;
  reason: string | null;
}
