/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type DoseState = typeof DoseState[keyof typeof DoseState];


export const DoseState = {
  GIVEN: 'GIVEN',
  OMITTED: 'OMITTED',
  PENDING: 'PENDING',
  OVERDUE: 'OVERDUE',
} as const;
