/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { EpisodeStatus } from './episodeStatus';

export interface EpisodeRead {
  id: string;
  patient_id: string;
  episode_number: string;
  status: EpisodeStatus;
  reason: string;
  opened_at: string;
  closed_at: string | null;
}
