/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type GetEffectivePracticeTariffApiV1PracticesPracticeIdTariffsEffectiveGetParams = {
payer_id?: string | null;
health_plan_id?: string | null;
on?: string | null;
};
