/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';
import type { DiagnosisStage } from './diagnosisStage';

export type GetMorbidityReportApiV1ReportsMorbidityGetParams = {
from_date?: string | null;
to_date?: string | null;
service_id?: string | null;
stage?: DiagnosisStage;
role?: DiagnosisRole | null;
/**
 * @pattern ^(CODE|CHAPTER)$
 */
group_by?: string;
};
