/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Alta de varias prácticas con las mismas condiciones, para armar la cartilla de un
 * capítulo entero sin cargarlo práctica por práctica.
 */
export interface HealthPlanPracticeBulkCreate {
  /**
     * @minItems 1
     * @maxItems 500
     */
  practice_ids: string[];
  is_covered?: boolean;
  waiting_period_days?: number | null;
  copayment_amount?: number | string;
  requires_authorization?: boolean;
  notes?: string | null;
}
