/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Cobertura de una práctica dentro de un plan.
 *
 * ``waiting_period_days`` vacío significa que el plan no pactó carencia propia y rige la
 * de la práctica.
 */
export interface HealthPlanPracticeCreate {
  practice_id: string;
  is_covered?: boolean;
  waiting_period_days?: number | null;
  copayment_amount?: number | string;
  requires_authorization?: boolean;
  notes?: string | null;
}
