/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ``waiting_period_days`` vacío devuelve la práctica a la carencia del nomenclador.
 */
export interface HealthPlanPracticeUpdate {
  is_covered?: boolean;
  waiting_period_days?: number | null;
  copayment_amount?: number | string;
  requires_authorization?: boolean;
  notes?: string | null;
}
