/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { HealthPlanPracticeRead } from './healthPlanPracticeRead';

/**
 * Resultado del alta masiva: lo que se agregó y lo que ya estaba en la cartilla.
 */
export interface HealthPlanPracticeBulkRead {
  created: HealthPlanPracticeRead[];
  skipped_practice_ids: string[];
}
