/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * The payer of a plan is not editable: moving a plan would move the coverages and the
 * tariffs already agreed under it.
 */
export interface HealthPlanUpdate {
  /**
     * @minLength 1
     * @maxLength 150
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 40
     */
  code: string;
}
