/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';
import type { DiagnosisStage } from './diagnosisStage';

export interface HospitalizationDiagnosisRead {
  id: string;
  hospitalization_id: string;
  diagnosis_code_id: string;
  code: string;
  description: string;
  role: DiagnosisRole;
  stage: DiagnosisStage;
  diagnosed_by_id: string | null;
  recorded_by_user_id: string | null;
  recorded_by_user_name: string | null;
  diagnosed_at: string;
  notes: string | null;
  created_at: string;
}
