/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';
import type { DiagnosisStage } from './diagnosisStage';

/**
 * Un diagnóstico que se le asienta a la internación.
 *
 * Se informa el código del catálogo —el ``id`` es interno— porque es lo que el médico
 * tiene a mano y lo que viaja en cualquier interconsulta.
 */
export interface HospitalizationDiagnosisCreate {
  /**
     * @minLength 1
     * @maxLength 10
     */
  code: string;
  role?: DiagnosisRole;
  stage?: DiagnosisStage;
  diagnosed_by_id?: string | null;
  diagnosed_at?: string | null;
  notes?: string | null;
}
