/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ChargeItemRead } from './chargeItemRead';
import type { PracticeOrderStatus } from './practiceOrderStatus';

export interface HospitalizationPracticeRead {
  id: string;
  hospitalization_id: string;
  practice_id: string;
  practice_code: string;
  practice_name: string;
  prescribed_by_id: string;
  performed_by_id: string | null;
  performed_by_user_id: string | null;
  performed_by_user_name: string | null;
  service_id: string | null;
  charge_item_id: string | null;
  status: PracticeOrderStatus;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  quantity: string;
  prescribed_at: string;
  performed_at: string | null;
  cancelled_at: string | null;
  indication: string | null;
  notes: string | null;
  authorization_number: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  copayment_amount: string;
  copayment_charge_item_id: string | null;
  coverage_override_reason: string | null;
  created_at: string;
  charge?: ChargeItemRead | null;
}
