/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { HospitalizationStatus } from './hospitalizationStatus';

export interface HospitalizationRead {
  id: string;
  patient_id: string;
  status: HospitalizationStatus;
  admission_reason: string;
  admitted_at: string | null;
}
