/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A hospitalization always originates in an admission request.
 */
export interface HospitalizationCreate {
  admission_id: string;
  facility_id?: string | null;
  responsible_service_id?: string | null;
  attending_physician_id?: string | null;
}
