/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * A practice indicated in a hospitalization.
 *
 * ``prescribed_by_id`` is the professional who indicated it. Informing ``performed_at``
 * registers the practice as already performed, which is what generates the charge;
 * ``unit_price`` overrides the tariff when the practice has no agreed value.
 */
export interface HospitalizationPracticeCreate {
  practice_id: string;
  prescribed_by_id: string;
  performed_by_id?: string | null;
  service_id?: string | null;
  quantity?: number | string;
  prescribed_at?: string | null;
  performed_at?: string | null;
  unit_price?: number | string | null;
  indication?: string | null;
  notes?: string | null;
  recorded_by?: string | null;
  authorization_number?: string | null;
  override_coverage_rules?: boolean;
  override_reason?: string | null;
}
