/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface HospitalizationPracticePerformCreate {
  performed_at?: string | null;
  performed_by_id?: string | null;
  unit_price?: number | string | null;
  recorded_by?: string | null;
  notes?: string | null;
  authorization_number?: string | null;
  override_coverage_rules?: boolean;
  override_reason?: string | null;
}
