/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type HospitalizationStatus = typeof HospitalizationStatus[keyof typeof HospitalizationStatus];


export const HospitalizationStatus = {
  PENDING_BED: 'PENDING_BED',
  IN_PROGRESS: 'IN_PROGRESS',
  CLINICALLY_DISCHARGED: 'CLINICALLY_DISCHARGED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
} as const;
