/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface HospitalizationCreate {
  patient_id: string;
  /**
     * @minLength 3
     * @maxLength 500
     */
  admission_reason: string;
}
