/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { HospitalizationEventReadDetails } from './hospitalizationEventReadDetails';
import type { HospitalizationEventType } from './hospitalizationEventType';

export interface HospitalizationEventRead {
  id: string;
  event_type: HospitalizationEventType;
  hospitalization_id: string | null;
  admission_id: string | null;
  bed_id: string | null;
  patient_id: string | null;
  occurred_at: string;
  actor: string | null;
  details: HospitalizationEventReadDetails;
}
