/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';

/**
 * El código no se corrige: se quita el diagnóstico y se asienta el que corresponde.
 */
export interface HospitalizationDiagnosisUpdate {
  role?: DiagnosisRole;
  diagnosed_by_id?: string | null;
  notes?: string | null;
}
