/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PracticeChapter } from './practiceChapter';

export type ListHealthPlanPracticesApiV1HealthPlansHealthPlanIdPracticesGetParams = {
chapter?: PracticeChapter | null;
search?: string | null;
only_covered?: boolean;
};
