/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisLevel } from './diagnosisLevel';

export type ListDiagnosesApiV1DiagnosesGetParams = {
search?: string | null;
chapter_code?: string | null;
parent_code?: string | null;
level?: DiagnosisLevel | null;
only_active?: boolean;
only_codifiable?: boolean;
limit?: number;
};
