/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisStage } from './diagnosisStage';

export type ListHospitalizationDiagnosesApiV1HospitalizationsHospitalizationIdDiagnosesGetParams = {
stage?: DiagnosisStage | null;
};
