/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ListMedicationRoundApiV1NursingMedicationsGetParams = {
hospitalization_id?: string | null;
service_id?: string | null;
ward?: string | null;
window_start?: string | null;
window_end?: string | null;
overdue_only?: boolean;
};
