/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ListNursingTasksApiV1NursingTasksGetParams = {
pending_only?: boolean;
hospitalization_id?: string | null;
patient_id?: string | null;
service_id?: string | null;
ward?: string | null;
on?: string | null;
};
