/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type ListAdmissionsApiV1AdmissionsGetParams = {
hospitalization_id?: string | null;
patient_id?: string | null;
};
