/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { Nomenclador } from './nomenclador';
import type { PracticeChapter } from './practiceChapter';
import type { PracticeSetting } from './practiceSetting';
import type { PracticeType } from './practiceType';

export type ListPracticesApiV1PracticesGetParams = {
nomenclador?: Nomenclador | null;
chapter?: PracticeChapter | null;
practice_type?: PracticeType | null;
setting?: PracticeSetting | null;
search?: string | null;
only_active?: boolean;
};
