/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface MedicalPracticeTariffUpdate {
  payer_id?: string | null;
  health_plan_id?: string | null;
  unit_value?: number | string | null;
  professional_fee?: number | string | null;
  expense_amount?: number | string | null;
  total_amount?: number | string | null;
  coinsurance?: number | string;
  /**
     * @minLength 3
     * @maxLength 3
     */
  currency?: string;
  valid_from: string;
  valid_until?: string | null;
  notes?: string | null;
}
