/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type MedicationRoute = typeof MedicationRoute[keyof typeof MedicationRoute];


export const MedicationRoute = {
  ORAL: 'ORAL',
  INTRAVENOUS: 'INTRAVENOUS',
  INTRAMUSCULAR: 'INTRAMUSCULAR',
  SUBCUTANEOUS: 'SUBCUTANEOUS',
  INHALATORY: 'INHALATORY',
  TOPICAL: 'TOPICAL',
  RECTAL: 'RECTAL',
  OTHER: 'OTHER',
} as const;
