/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface MedicalPracticeTariffRead {
  id: string;
  practice_id: string;
  payer_id: string | null;
  health_plan_id: string | null;
  unit_value: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  professional_fee: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  expense_amount: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  total_amount: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  coinsurance: string;
  currency: string;
  valid_from: string;
  valid_until: string | null;
  notes: string | null;
  created_at: string;
}
