/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DoseSlotRead } from './doseSlotRead';
import type { MedicationRoute } from './medicationRoute';
import type { ScheduleKind } from './scheduleKind';
import type { TreatmentKind } from './treatmentKind';

/**
 * Una indicación activa vista desde el pasillo: a quién, qué y cuándo fue la última.
 */
export interface MedicationRoundRead {
  treatment_id: string;
  hospitalization_id: string;
  patient_id: string;
  patient_name: string;
  ward: string | null;
  room_code: string | null;
  bed_code: string | null;
  service_id: string | null;
  service_name: string | null;
  kind: TreatmentKind;
  description: string;
  presentation: string | null;
  dose: string | null;
  route: MedicationRoute | null;
  frequency: string | null;
  schedule_kind: ScheduleKind;
  interval_hours: number | null;
  times_of_day: string[] | null;
  started_at: string;
  last_administered_at: string | null;
  administrations: number;
  next_due_at: string | null;
  overdue: boolean;
  slots: DoseSlotRead[];
}
