/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { Nomenclador } from './nomenclador';
import type { PracticeChapter } from './practiceChapter';
import type { PracticeSetting } from './practiceSetting';
import type { PracticeType } from './practiceType';

export interface MedicalPracticeCreate {
  nomenclador?: Nomenclador;
  /**
     * @minLength 1
     * @maxLength 20
     */
  code: string;
  /**
     * @minLength 1
     * @maxLength 250
     */
  name: string;
  description?: string | null;
  chapter: PracticeChapter;
  practice_type: PracticeType;
  setting?: PracticeSetting;
  galeno_units?: number | string;
  expense_units?: number | string;
  anesthesia_units?: number | string;
  biochemical_units?: number | string;
  radiology_units?: number | string;
  requires_authorization?: boolean;
  requires_consent?: boolean;
  is_nursing_task?: boolean;
  /**
     * @minimum 0
     * @maximum 3650
     */
  default_waiting_period_days?: number;
  is_active?: boolean;
  valid_from?: string | null;
  valid_until?: string | null;
  notes?: string | null;
}
