/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { Nomenclador } from './nomenclador';
import type { PracticeChapter } from './practiceChapter';
import type { PracticeSetting } from './practiceSetting';
import type { PracticeType } from './practiceType';

export interface MedicalPracticeRead {
  id: string;
  nomenclador: Nomenclador;
  code: string;
  name: string;
  description: string | null;
  chapter: PracticeChapter;
  practice_type: PracticeType;
  setting: PracticeSetting;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  galeno_units: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  expense_units: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  anesthesia_units: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  biochemical_units: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  radiology_units: string;
  requires_authorization: boolean;
  requires_consent: boolean;
  is_nursing_task: boolean;
  default_waiting_period_days: number;
  is_active: boolean;
  valid_from: string | null;
  valid_until: string | null;
  notes: string | null;
  created_at: string;
}
