/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';
import type { DiagnosisStage } from './diagnosisStage';
import type { MorbidityRowRead } from './morbidityRowRead';

export interface MorbidityReportRead {
  from_date: string | null;
  to_date: string | null;
  stage: DiagnosisStage;
  role: DiagnosisRole | null;
  group_by: string;
  total_episodes: number;
  uncoded_episodes: number;
  rows: MorbidityRowRead[];
}
