/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface MorbidityRowRead {
  key: string;
  description: string;
  episodes: number;
  patients: number;
  deaths: number;
  average_stay_days: number | null;
  mortality_rate: number;
}
