/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PracticeOrderStatus } from './practiceOrderStatus';

/**
 * Una tarea del panel de enfermería, con el paciente y dónde está.
 */
export interface NursingTaskRead {
  id: string;
  hospitalization_id: string;
  practice_id: string;
  practice_code: string;
  practice_name: string;
  status: PracticeOrderStatus;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  quantity: string;
  patient_id: string;
  patient_name: string;
  ward: string | null;
  room_code: string | null;
  bed_code: string | null;
  service_id: string | null;
  service_name: string | null;
  prescribed_by: string | null;
  prescribed_at: string;
  performed_at: string | null;
  performed_by: string | null;
  cancelled_at: string | null;
  indication: string | null;
  notes: string | null;
}
