/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PrescriptionKind } from './prescriptionKind';

export interface PatientPrescriptionRead {
  hospitalization_id: string;
  kind: PrescriptionKind;
  description: string;
  presentation: string | null;
  dosage: string | null;
  duration_days: number | null;
  instructions: string | null;
  prescribed_at: string;
}
