/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface PatientContactCreate {
  /**
     * @minLength 1
     * @maxLength 150
     */
  full_name: string;
  relationship_to_patient?: string | null;
  phone?: string | null;
  email?: string | null;
  is_primary?: boolean;
}
