/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PatientRead } from './patientRead';

/**
 * Candidate patient found while searching identifiers before creating a new one.
 */
export interface PatientMatchRead {
  patient: PatientRead;
  matched_on: string;
}
