/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { AdmissionType } from './admissionType';
import type { HospitalizationStatus } from './hospitalizationStatus';

/**
 * Una internación del paciente, resumida para la línea de tiempo.
 */
export interface PatientStayRead {
  hospitalization_id: string;
  status: HospitalizationStatus;
  admission_type: AdmissionType | null;
  admitted_at: string | null;
  clinically_discharged_at: string | null;
  administratively_discharged_at: string | null;
  admission_reason: string;
  facility_name: string | null;
  service_name: string | null;
  bed_label: string | null;
  principal_diagnosis: string | null;
  length_of_stay_days: number | null;
}
