/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { ClinicalNoteKind } from './clinicalNoteKind';

export interface PatientNoteRead {
  hospitalization_id: string;
  kind: ClinicalNoteKind;
  note: string;
  noted_at: string;
  recorded_by_user_name: string | null;
}
