/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { CoverageStatus } from './coverageStatus';

/**
 * The patient of a coverage is not editable; everything else is.
 */
export interface PatientCoverageUpdate {
  payer_id?: string | null;
  health_plan_id?: string | null;
  payer_name?: string | null;
  plan_name?: string | null;
  member_number?: string | null;
  authorization_required?: boolean;
  valid_from?: string | null;
  valid_until?: string | null;
  status?: CoverageStatus;
}
