/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PatientIdentifierType } from './patientIdentifierType';

export interface PatientIdentifierRead {
  id: string;
  patient_id: string;
  identifier_type: PatientIdentifierType;
  value: string;
  issuer: string | null;
  is_primary: boolean;
  created_at: string;
}
