/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PatientIdentifierType } from './patientIdentifierType';

export interface PatientIdentifierCreate {
  identifier_type: PatientIdentifierType;
  /**
     * @minLength 1
     * @maxLength 80
     */
  value: string;
  issuer?: string | null;
  is_primary?: boolean;
}
