/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type PatientIdentifierType = typeof PatientIdentifierType[keyof typeof PatientIdentifierType];


export const PatientIdentifierType = {
  DNI: 'DNI',
  PASSPORT: 'PASSPORT',
  MEDICAL_RECORD_NUMBER: 'MEDICAL_RECORD_NUMBER',
  SOCIAL_SECURITY: 'SOCIAL_SECURITY',
  EXTERNAL: 'EXTERNAL',
  OTHER: 'OTHER',
} as const;
