/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface PatientCoverageRead {
  id: string;
  patient_id: string;
  payer_name: string;
  plan_name: string | null;
  member_number: string | null;
  authorization_required: boolean;
  created_at: string;
}
