/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PatientCoverageRead } from './patientCoverageRead';
import type { PatientDiagnosisRead } from './patientDiagnosisRead';
import type { PatientNoteRead } from './patientNoteRead';
import type { PatientPaymentRead } from './patientPaymentRead';
import type { PatientPracticeRead } from './patientPracticeRead';
import type { PatientPrescriptionRead } from './patientPrescriptionRead';
import type { PatientRead } from './patientRead';
import type { PatientRecordTotals } from './patientRecordTotals';
import type { PatientStayRead } from './patientStayRead';
import type { PatientTreatmentRead } from './patientTreatmentRead';

export interface PatientRecordRead {
  patient: PatientRead;
  age: number | null;
  coverages: PatientCoverageRead[];
  totals: PatientRecordTotals;
  stays: PatientStayRead[];
  diagnoses: PatientDiagnosisRead[];
  practices: PatientPracticeRead[];
  prescriptions: PatientPrescriptionRead[];
  treatments: PatientTreatmentRead[];
  notes: PatientNoteRead[];
  payments: PatientPaymentRead[];
}
