/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { DiagnosisRole } from './diagnosisRole';
import type { DiagnosisStage } from './diagnosisStage';

export interface PatientDiagnosisRead {
  hospitalization_id: string;
  code: string;
  description: string;
  role: DiagnosisRole;
  stage: DiagnosisStage;
  diagnosed_at: string;
  notes: string | null;
}
