/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lo que la admisión le manda al financiador para validar el código.
 */
export interface PayerAuthorizationRequest {
  health_plan_id: string;
  /** @maxLength 20 */
  authorization_code: string;
  practice_id?: string | null;
  member_number?: string | null;
  on?: string | null;
}
