/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PayerAuthorizationResult } from './payerAuthorizationResult';

/**
 * Respuesta del financiador, con la plata que queda a cargo del paciente.
 */
export interface PayerAuthorizationRead {
  authorized: boolean;
  result: PayerAuthorizationResult;
  authorization_code: string;
  authorization_number: string | null;
  valid_until: string | null;
  message: string;
  payer_id: string;
  payer_name: string;
  health_plan_id: string;
  plan_name: string;
  practice_id: string | null;
  practice_code: string | null;
  practice_name: string | null;
  plan_covers_practice: boolean | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  copayment_amount: string;
  private_amount: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  patient_due: string;
  currency: string;
}
