/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Qué contestó el financiador al código que trajo el afiliado.
 */
export type PayerAuthorizationResult = typeof PayerAuthorizationResult[keyof typeof PayerAuthorizationResult];


export const PayerAuthorizationResult = {
  AUTHORIZED: 'AUTHORIZED',
  REJECTED: 'REJECTED',
  INVALID_CODE: 'INVALID_CODE',
  UNKNOWN_CODE: 'UNKNOWN_CODE',
  NOT_COVERED: 'NOT_COVERED',
} as const;
