/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface PayerRead {
  id: string;
  name: string;
  code: string;
  tax_id: string | null;
  created_at: string;
}
