/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentMethod } from './paymentMethod';

/**
 * Un cobro al paciente contra la cuenta de la internación.
 */
export interface PaymentCreate {
  amount: number | string;
  method?: PaymentMethod;
  paid_at?: string | null;
  received_by?: string | null;
  reference?: string | null;
  notes?: string | null;
}
