/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PaymentMethod } from './paymentMethod';
import type { PaymentStatus } from './paymentStatus';

export interface PaymentRead {
  id: string;
  account_id: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  amount: string;
  method: PaymentMethod;
  status: PaymentStatus;
  paid_at: string;
  received_by: string | null;
  reference: string | null;
  notes: string | null;
  voided_at?: string | null;
  voided_by?: string | null;
  void_reason?: string | null;
}
