/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Un pago mal cargado se anula, no se borra.
 */
export interface PaymentVoidCreate {
  reason?: string | null;
  actor?: string | null;
}
