/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface PhysicalDepartureCreate {
  departed_at?: string | null;
  released_by?: string | null;
  notes?: string | null;
}
