/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Por qué la cartilla deja pasar (o no) una práctica.
 */
export type PlanCoverageStatus = typeof PlanCoverageStatus[keyof typeof PlanCoverageStatus];


export const PlanCoverageStatus = {
  NO_COVERAGE: 'NO_COVERAGE',
  NO_PLAN: 'NO_PLAN',
  NO_CARTILLA: 'NO_CARTILLA',
  NOT_LISTED: 'NOT_LISTED',
  NOT_COVERED: 'NOT_COVERED',
  WAITING_PERIOD: 'WAITING_PERIOD',
  COVERED: 'COVERED',
} as const;
