/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PlanCoverageStatus } from './planCoverageStatus';

/**
 * Lo que la cartilla del plan dice sobre una práctica antes de indicarla.
 */
export interface PlanCoverageCheckRead {
  status: PlanCoverageStatus;
  blocked: boolean;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  copayment_amount: string;
  requires_authorization: boolean;
  waiting_period_days: number;
  available_from: string | null;
  health_plan_id: string | null;
  message: string | null;
}
