/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type PracticeOrderStatus = typeof PracticeOrderStatus[keyof typeof PracticeOrderStatus];


export const PracticeOrderStatus = {
  REQUESTED: 'REQUESTED',
  PERFORMED: 'PERFORMED',
  CANCELLED: 'CANCELLED',
} as const;
