/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { SpecialtyRead } from './specialtyRead';

export interface ProfessionalSpecialtyRead {
  id: string;
  specialty_id: string;
  specialty: SpecialtyRead;
  license_number: string;
  created_at: string;
}
