/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface ProfessionalSpecialtyCreate {
  specialty_id: string;
  /**
     * @minLength 1
     * @maxLength 80
     */
  license_number: string;
}
