/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Quién paga un cargo: el financiador por convenio, o el paciente de su bolsillo.
 */
export type ResponsibleParty = typeof ResponsibleParty[keyof typeof ResponsibleParty];


export const ResponsibleParty = {
  PAYER: 'PAYER',
  PATIENT: 'PATIENT',
} as const;
