/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomStatus } from './roomStatus';

export interface RoomRead {
  id: string;
  facility_id: string;
  code: string;
  ward: string;
  status: RoomStatus;
  created_at: string;
}
