/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomStatus } from './roomStatus';

/**
 * ``status`` es el estado real: sale de las camas de la habitación.
 *
 * ``administrative_status`` es lo que se dejó escrito sobre la habitación misma, que solo
 * manda cuando está bloqueada o en mantenimiento.
 */
export interface RoomRead {
  id: string;
  facility_id: string;
  code: string;
  ward: string;
  status: RoomStatus;
  administrative_status: RoomStatus;
  beds?: number;
  available_beds?: number;
  reserved_beds?: number;
  occupied_beds?: number;
  cleaning_beds?: number;
  unavailable_beds?: number;
  created_at: string;
}
