/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { RoomStatus } from './roomStatus';

export interface RoomCreate {
  facility_id: string;
  /**
     * @minLength 1
     * @maxLength 50
     */
  code: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  ward: string;
  status?: RoomStatus;
}
