/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Cómo se reparte en el tiempo lo que hay que dar.
 *
 * Es lo que permite calcular la próxima toma y saber cuál se pasó de hora. Sin esto la
 * frecuencia es una frase que el sistema no puede leer.
 */
export type ScheduleKind = typeof ScheduleKind[keyof typeof ScheduleKind];


export const ScheduleKind = {
  INTERVAL: 'INTERVAL',
  TIMES: 'TIMES',
  ONCE: 'ONCE',
  AS_NEEDED: 'AS_NEEDED',
  CONTINUOUS: 'CONTINUOUS',
} as const;
