/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export type SearchAvailableBedsApiV1BedsAvailableGetParams = {
facility_id?: string | null;
ward?: string | null;
room_id?: string | null;
};
