/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { PatientIdentifierType } from './patientIdentifierType';

export type SearchPatientsApiV1PatientsSearchGetParams = {
value: string;
identifier_type?: PatientIdentifierType | null;
};
