/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface ServiceAssignmentCreate {
  service_id: string;
  reason?: string | null;
  assigned_by?: string | null;
}
