/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */

export interface ServiceAssignmentRead {
  id: string;
  hospitalization_id: string;
  service_id: string;
  started_at: string;
  ended_at: string | null;
  reason: string | null;
  assigned_by: string | null;
}
