/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { Permission } from './permission';
import type { UserRead } from './userRead';

/**
 * Lo que necesita el cliente para operar: quién es y qué puede hacer.
 */
export interface SessionRead {
  token: string;
  expires_at: string;
  user: UserRead;
  permissions: Permission[];
}
