/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { TreatmentStatus } from './treatmentStatus';

/**
 * Cortar una indicación: suspendida antes de tiempo o cumplida.
 */
export interface TreatmentStopCreate {
  status?: TreatmentStatus;
  ended_at?: string | null;
  reason?: string | null;
}
