/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { MedicationRoute } from './medicationRoute';
import type { ScheduleKind } from './scheduleKind';
import type { TreatmentKind } from './treatmentKind';
import type { TreatmentStatus } from './treatmentStatus';

export interface TreatmentRead {
  id: string;
  hospitalization_id: string;
  kind: TreatmentKind;
  description: string;
  presentation: string | null;
  dose: string | null;
  route: MedicationRoute | null;
  frequency: string | null;
  schedule_kind: ScheduleKind;
  interval_hours: number | null;
  times_of_day: string[] | null;
  status: TreatmentStatus;
  started_at: string;
  ended_at: string | null;
  end_reason: string | null;
  prescribed_by_id: string | null;
  recorded_by_user_id: string | null;
  recorded_by_user_name: string | null;
  indication: string | null;
  created_at: string;
}
