/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type { MedicationRoute } from './medicationRoute';
import type { ScheduleKind } from './scheduleKind';
import type { TreatmentKind } from './treatmentKind';

/**
 * Lo que se le empieza a dar al paciente.
 */
export interface TreatmentCreate {
  kind?: TreatmentKind;
  /**
     * @minLength 1
     * @maxLength 250
     */
  description: string;
  presentation?: string | null;
  dose?: string | null;
  route?: MedicationRoute | null;
  frequency?: string | null;
  started_at?: string | null;
  prescribed_by_id?: string | null;
  indication?: string | null;
  schedule_kind?: ScheduleKind;
  interval_hours?: number | null;
  times_of_day?: string[] | null;
}
