/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AdministrationCreate,
  AdministrationRead,
  AdministrationVoidCreate,
  ClinicalNoteCreate,
  ClinicalNoteRead,
  ClinicalNoteVoidCreate,
  ListNotesApiV1HospitalizationsHospitalizationIdNotesGetParams,
  ListTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGetParams,
  TreatmentCreate,
  TreatmentRead,
  TreatmentStopCreate,
  TreatmentUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTreatments = () => {
/**
 * Medicación y tratamientos de la internación; primero lo que se está dando ahora.
 * @summary List Treatments
 */
const listTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGet = (
    hospitalizationId: string,
    params?: ListTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGetParams,
 options?: SecondParameter<typeof customInstance<TreatmentRead[]>>,) => {
      return customInstance<TreatmentRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Indica medicación o un tratamiento en curso.
 *
 * Con el alta médica dada la internación no recibe más cambios, salvo de un administrador.
 * @summary Add Treatment
 */
const addTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsPost = (
    hospitalizationId: string,
    treatmentCreate: TreatmentCreate,
 options?: SecondParameter<typeof customInstance<TreatmentRead>>,) => {
      return customInstance<TreatmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: treatmentCreate
    },
      options);
    }
  /**
 * Corrige la indicación en curso. Una ya cerrada no se edita: se indica de nuevo.
 * @summary Update Treatment
 */
const updateTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdPut = (
    hospitalizationId: string,
    treatmentId: string,
    treatmentUpdate: TreatmentUpdate,
 options?: SecondParameter<typeof customInstance<TreatmentRead>>,) => {
      return customInstance<TreatmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments/${treatmentId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: treatmentUpdate
    },
      options);
    }
  /**
 * Corta lo que se estaba dando: suspendido antes de tiempo o cumplido.
 * @summary Stop Treatment
 */
const stopTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdStopPost = (
    hospitalizationId: string,
    treatmentId: string,
    treatmentStopCreate: TreatmentStopCreate,
 options?: SecondParameter<typeof customInstance<TreatmentRead>>,) => {
      return customInstance<TreatmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments/${treatmentId}/stop`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: treatmentStopCreate
    },
      options);
    }
  /**
 * Las tomas registradas de una indicación, la última arriba.
 * @summary List Administrations
 */
const listAdministrationsApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsGet = (
    hospitalizationId: string,
    treatmentId: string,
 options?: SecondParameter<typeof customInstance<AdministrationRead[]>>,) => {
      return customInstance<AdministrationRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments/${treatmentId}/administrations`, method: 'GET'
    },
      options);
    }
  /**
 * Registra una toma: dada, o no dada con su motivo.
 *
 * Sin dosis toma la de la indicación, que es lo que se da habitualmente.
 * @summary Register Administration
 */
const registerAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsPost = (
    hospitalizationId: string,
    treatmentId: string,
    administrationCreate: AdministrationCreate,
 options?: SecondParameter<typeof customInstance<AdministrationRead>>,) => {
      return customInstance<AdministrationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments/${treatmentId}/administrations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: administrationCreate
    },
      options);
    }
  /**
 * Anula una toma cargada por error; queda registrada como anulada.
 * @summary Void Administration
 */
const voidAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsAdministrationIdVoidPost = (
    hospitalizationId: string,
    treatmentId: string,
    administrationId: string,
    administrationVoidCreate: AdministrationVoidCreate,
 options?: SecondParameter<typeof customInstance<AdministrationRead>>,) => {
      return customInstance<AdministrationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/treatments/${treatmentId}/administrations/${administrationId}/void`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: administrationVoidCreate
    },
      options);
    }
  /**
 * Evoluciones, observaciones e interconsultas, lo último arriba.
 * @summary List Notes
 */
const listNotesApiV1HospitalizationsHospitalizationIdNotesGet = (
    hospitalizationId: string,
    params?: ListNotesApiV1HospitalizationsHospitalizationIdNotesGetParams,
 options?: SecondParameter<typeof customInstance<ClinicalNoteRead[]>>,) => {
      return customInstance<ClinicalNoteRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/notes`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Escribe una evolución, una observación o la atención de otro médico.
 * @summary Add Note
 */
const addNoteApiV1HospitalizationsHospitalizationIdNotesPost = (
    hospitalizationId: string,
    clinicalNoteCreate: ClinicalNoteCreate,
 options?: SecondParameter<typeof customInstance<ClinicalNoteRead>>,) => {
      return customInstance<ClinicalNoteRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/notes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clinicalNoteCreate
    },
      options);
    }
  /**
 * Anula una nota cargada por error; el texto queda en la historia.
 * @summary Void Note
 */
const voidNoteApiV1HospitalizationsHospitalizationIdNotesNoteIdVoidPost = (
    hospitalizationId: string,
    noteId: string,
    clinicalNoteVoidCreate: ClinicalNoteVoidCreate,
 options?: SecondParameter<typeof customInstance<ClinicalNoteRead>>,) => {
      return customInstance<ClinicalNoteRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/notes/${noteId}/void`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: clinicalNoteVoidCreate
    },
      options);
    }
  return {listTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGet,addTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsPost,updateTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdPut,stopTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdStopPost,listAdministrationsApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsGet,registerAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsPost,voidAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsAdministrationIdVoidPost,listNotesApiV1HospitalizationsHospitalizationIdNotesGet,addNoteApiV1HospitalizationsHospitalizationIdNotesPost,voidNoteApiV1HospitalizationsHospitalizationIdNotesNoteIdVoidPost}};
export type ListTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['listTreatmentsApiV1HospitalizationsHospitalizationIdTreatmentsGet']>>>
export type AddTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['addTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsPost']>>>
export type UpdateTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['updateTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdPut']>>>
export type StopTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdStopPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['stopTreatmentApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdStopPost']>>>
export type ListAdministrationsApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['listAdministrationsApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsGet']>>>
export type RegisterAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['registerAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsPost']>>>
export type VoidAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsAdministrationIdVoidPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['voidAdministrationApiV1HospitalizationsHospitalizationIdTreatmentsTreatmentIdAdministrationsAdministrationIdVoidPost']>>>
export type ListNotesApiV1HospitalizationsHospitalizationIdNotesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['listNotesApiV1HospitalizationsHospitalizationIdNotesGet']>>>
export type AddNoteApiV1HospitalizationsHospitalizationIdNotesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['addNoteApiV1HospitalizationsHospitalizationIdNotesPost']>>>
export type VoidNoteApiV1HospitalizationsHospitalizationIdNotesNoteIdVoidPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTreatments>['voidNoteApiV1HospitalizationsHospitalizationIdNotesNoteIdVoidPost']>>>
