/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  PayerAuthorizationRead,
  PayerAuthorizationRequest
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getPayerMock = () => {
/**
 * Simula la respuesta del financiador al código de autorización de 3 dígitos.
 *
 * Contesta si la práctica queda habilitada, con qué copago la cubre la cartilla del plan
 * y, cuando no la autoriza, cuánto sale hacerla en forma particular.
 * @summary Verify Payer Authorization
 */
const verifyPayerAuthorizationApiV1PayerMockAuthorizationsPost = (
    payerAuthorizationRequest: PayerAuthorizationRequest,
 options?: SecondParameter<typeof customInstance<PayerAuthorizationRead>>,) => {
      return customInstance<PayerAuthorizationRead>(
      {url: `/api/v1/payer-mock/authorizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: payerAuthorizationRequest
    },
      options);
    }
  return {verifyPayerAuthorizationApiV1PayerMockAuthorizationsPost}};
export type VerifyPayerAuthorizationApiV1PayerMockAuthorizationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPayerMock>['verifyPayerAuthorizationApiV1PayerMockAuthorizationsPost']>>>
