/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AuthorizationRead,
  AuthorizationRequestCreate,
  AuthorizationResolveCreate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuthorizations = () => {
/**
 * @summary List Admission Authorizations
 */
const listAdmissionAuthorizationsApiV1AdmissionsAdmissionIdAuthorizationsGet = (
    admissionId: string,
 options?: SecondParameter<typeof customInstance<AuthorizationRead[]>>,) => {
      return customInstance<AuthorizationRead[]>(
      {url: `/api/v1/admissions/${admissionId}/authorizations`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Request Admission Authorization
 */
const requestAdmissionAuthorizationApiV1AdmissionsAdmissionIdAuthorizationsPost = (
    admissionId: string,
    authorizationRequestCreate: AuthorizationRequestCreate,
 options?: SecondParameter<typeof customInstance<AuthorizationRead>>,) => {
      return customInstance<AuthorizationRead>(
      {url: `/api/v1/admissions/${admissionId}/authorizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authorizationRequestCreate
    },
      options);
    }
  /**
 * Record the payer answer; an authorized admission moves on to the bed search.
 * @summary Resolve Authorization
 */
const resolveAuthorizationApiV1AuthorizationsAuthorizationIdResolvePost = (
    authorizationId: string,
    authorizationResolveCreate: AuthorizationResolveCreate,
 options?: SecondParameter<typeof customInstance<AuthorizationRead>>,) => {
      return customInstance<AuthorizationRead>(
      {url: `/api/v1/authorizations/${authorizationId}/resolve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authorizationResolveCreate
    },
      options);
    }
  /**
 * @summary List Hospitalization Authorizations
 */
const listHospitalizationAuthorizationsApiV1HospitalizationsHospitalizationIdAuthorizationsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<AuthorizationRead[]>>,) => {
      return customInstance<AuthorizationRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/authorizations`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Request Hospitalization Authorization
 */
const requestHospitalizationAuthorizationApiV1HospitalizationsHospitalizationIdAuthorizationsPost = (
    hospitalizationId: string,
    authorizationRequestCreate: AuthorizationRequestCreate,
 options?: SecondParameter<typeof customInstance<AuthorizationRead>>,) => {
      return customInstance<AuthorizationRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/authorizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: authorizationRequestCreate
    },
      options);
    }
  return {listAdmissionAuthorizationsApiV1AdmissionsAdmissionIdAuthorizationsGet,requestAdmissionAuthorizationApiV1AdmissionsAdmissionIdAuthorizationsPost,resolveAuthorizationApiV1AuthorizationsAuthorizationIdResolvePost,listHospitalizationAuthorizationsApiV1HospitalizationsHospitalizationIdAuthorizationsGet,requestHospitalizationAuthorizationApiV1HospitalizationsHospitalizationIdAuthorizationsPost}};
export type ListAdmissionAuthorizationsApiV1AdmissionsAdmissionIdAuthorizationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthorizations>['listAdmissionAuthorizationsApiV1AdmissionsAdmissionIdAuthorizationsGet']>>>
export type RequestAdmissionAuthorizationApiV1AdmissionsAdmissionIdAuthorizationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthorizations>['requestAdmissionAuthorizationApiV1AdmissionsAdmissionIdAuthorizationsPost']>>>
export type ResolveAuthorizationApiV1AuthorizationsAuthorizationIdResolvePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthorizations>['resolveAuthorizationApiV1AuthorizationsAuthorizationIdResolvePost']>>>
export type ListHospitalizationAuthorizationsApiV1HospitalizationsHospitalizationIdAuthorizationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthorizations>['listHospitalizationAuthorizationsApiV1HospitalizationsHospitalizationIdAuthorizationsGet']>>>
export type RequestHospitalizationAuthorizationApiV1HospitalizationsHospitalizationIdAuthorizationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthorizations>['requestHospitalizationAuthorizationApiV1HospitalizationsHospitalizationIdAuthorizationsPost']>>>
