/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  HospitalizationPracticeCancelCreate,
  HospitalizationPracticePerformCreate,
  HospitalizationPracticeRead,
  ListNursingTasksApiV1NursingTasksGetParams,
  NursingTaskRead
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getNursing = () => {
/**
 * Lo que el médico indicó y enfermería todavía tiene que hacer.
 *
 * ``pending_only=false`` con ``on`` muestra además lo aplicado o cancelado ese día, que es
 * lo que se revisa al cerrar un turno.
 * @summary List Nursing Tasks
 */
const listNursingTasksApiV1NursingTasksGet = (
    params?: ListNursingTasksApiV1NursingTasksGetParams,
 options?: SecondParameter<typeof customInstance<NursingTaskRead[]>>,) => {
      return customInstance<NursingTaskRead[]>(
      {url: `/api/v1/nursing-tasks`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Marcar la tarea como aplicada: genera el cargo y queda en el historial.
 * @summary Perform Nursing Task
 */
const performNursingTaskApiV1NursingTasksOrderIdPerformPost = (
    orderId: string,
    hospitalizationPracticePerformCreate: HospitalizationPracticePerformCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/nursing-tasks/${orderId}/perform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticePerformCreate
    },
      options);
    }
  /**
 * Cancelar la tarea, con el motivo por el que no se aplicó.
 * @summary Cancel Nursing Task
 */
const cancelNursingTaskApiV1NursingTasksOrderIdCancelPost = (
    orderId: string,
    hospitalizationPracticeCancelCreate: HospitalizationPracticeCancelCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/nursing-tasks/${orderId}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticeCancelCreate
    },
      options);
    }
  return {listNursingTasksApiV1NursingTasksGet,performNursingTaskApiV1NursingTasksOrderIdPerformPost,cancelNursingTaskApiV1NursingTasksOrderIdCancelPost}};
export type ListNursingTasksApiV1NursingTasksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['listNursingTasksApiV1NursingTasksGet']>>>
export type PerformNursingTaskApiV1NursingTasksOrderIdPerformPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['performNursingTaskApiV1NursingTasksOrderIdPerformPost']>>>
export type CancelNursingTaskApiV1NursingTasksOrderIdCancelPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['cancelNursingTaskApiV1NursingTasksOrderIdCancelPost']>>>
