/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  HospitalizationPracticeCancelCreate,
  HospitalizationPracticePerformCreate,
  HospitalizationPracticeRead,
  ListMedicationRoundApiV1NursingMedicationsGetParams,
  ListNursingTasksApiV1NursingTasksGetParams,
  MedicationRoundRead,
  NursingTaskRead
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getNursing = () => {
/**
 * Lo que el médico indicó y enfermería tiene que hacer, o ya hizo.
 *
 * - Sin parámetros: lo pendiente de las internaciones activas.
 * - ``pending_only=false`` con ``on``: lo de ese día, para cerrar el turno.
 * - ``pending_only=false`` sin ``on``: el historial, que incluye internaciones cerradas.
 *
 * ``patient_id`` y ``service_id`` acotan por paciente y por servicio responsable.
 * @summary List Nursing Tasks
 */
const listNursingTasksApiV1NursingTasksGet = (
    params?: ListNursingTasksApiV1NursingTasksGetParams,
 options?: SecondParameter<typeof customInstance<NursingTaskRead[]>>,) => {
      return customInstance<NursingTaskRead[]>(
      {url: `/api/v1/nursing-tasks`, method: 'GET',
        params
    },
      options);
    }
  /**
 * Marcar la tarea como aplicada: genera el cargo y queda en el historial.
 * @summary Perform Nursing Task
 */
const performNursingTaskApiV1NursingTasksOrderIdPerformPost = (
    orderId: string,
    hospitalizationPracticePerformCreate: HospitalizationPracticePerformCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/nursing-tasks/${orderId}/perform`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticePerformCreate
    },
      options);
    }
  /**
 * Cancelar la tarea, con el motivo por el que no se aplicó.
 * @summary Cancel Nursing Task
 */
const cancelNursingTaskApiV1NursingTasksOrderIdCancelPost = (
    orderId: string,
    hospitalizationPracticeCancelCreate: HospitalizationPracticeCancelCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationPracticeRead>>,) => {
      return customInstance<HospitalizationPracticeRead>(
      {url: `/api/v1/nursing-tasks/${orderId}/cancel`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationPracticeCancelCreate
    },
      options);
    }
  /**
 * La vuelta de medicación: indicaciones activas de internaciones activas, con sus
 * horarios calculados.
 *
 * Cada indicación trae la línea de tiempo de la ventana —lo que se dio, lo que se omitió
 * y lo que falta—, el próximo horario y si está vencida. Sin ventana son las doce horas
 * para atrás y las doce para adelante. Primero lo vencido.
 * @summary List Medication Round
 */
const listMedicationRoundApiV1NursingMedicationsGet = (
    params?: ListMedicationRoundApiV1NursingMedicationsGetParams,
 options?: SecondParameter<typeof customInstance<MedicationRoundRead[]>>,) => {
      return customInstance<MedicationRoundRead[]>(
      {url: `/api/v1/nursing-medications`, method: 'GET',
        params
    },
      options);
    }
  return {listNursingTasksApiV1NursingTasksGet,performNursingTaskApiV1NursingTasksOrderIdPerformPost,cancelNursingTaskApiV1NursingTasksOrderIdCancelPost,listMedicationRoundApiV1NursingMedicationsGet}};
export type ListNursingTasksApiV1NursingTasksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['listNursingTasksApiV1NursingTasksGet']>>>
export type PerformNursingTaskApiV1NursingTasksOrderIdPerformPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['performNursingTaskApiV1NursingTasksOrderIdPerformPost']>>>
export type CancelNursingTaskApiV1NursingTasksOrderIdCancelPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['cancelNursingTaskApiV1NursingTasksOrderIdCancelPost']>>>
export type ListMedicationRoundApiV1NursingMedicationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNursing>['listMedicationRoundApiV1NursingMedicationsGet']>>>
