/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  PatientRecordRead
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getPatientRecord = () => {
/**
 * Todo lo del paciente en una sola respuesta: internaciones, diagnósticos,
 * prácticas y consultas, medicación indicada al alta y pagos.
 * @summary Get Patient Record
 */
const getPatientRecordApiV1PatientsPatientIdRecordGet = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<PatientRecordRead>>,) => {
      return customInstance<PatientRecordRead>(
      {url: `/api/v1/patients/${patientId}/record`, method: 'GET'
    },
      options);
    }
  return {getPatientRecordApiV1PatientsPatientIdRecordGet}};
export type GetPatientRecordApiV1PatientsPatientIdRecordGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPatientRecord>['getPatientRecordApiV1PatientsPatientIdRecordGet']>>>
