/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetMorbidityReportApiV1ReportsMorbidityGetParams,
  MorbidityReportRead
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getReports = () => {
/**
 * Egresos por diagnóstico CIE-10, con pacientes, estadía promedio y fallecidos.
 *
 * Se cuenta sobre los egresos del período y, por omisión, por el diagnóstico principal
 * de egreso. ``role`` vacío cuenta todos los diagnósticos, con lo que una internación
 * puede aparecer en varias filas.
 * @summary Get Morbidity Report
 */
const getMorbidityReportApiV1ReportsMorbidityGet = (
    params?: GetMorbidityReportApiV1ReportsMorbidityGetParams,
 options?: SecondParameter<typeof customInstance<MorbidityReportRead>>,) => {
      return customInstance<MorbidityReportRead>(
      {url: `/api/v1/reports/morbidity`, method: 'GET',
        params
    },
      options);
    }
  return {getMorbidityReportApiV1ReportsMorbidityGet}};
export type GetMorbidityReportApiV1ReportsMorbidityGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['getMorbidityReportApiV1ReportsMorbidityGet']>>>
