/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AdministrativeDischargeCreate,
  AdmissionCreate,
  AdmissionDashboardRead,
  AdmissionRead,
  BedAssignmentCreate,
  BedAssignmentRead,
  BedCreate,
  BedRead,
  BedRoomAssignmentCreate,
  BedStatusCreate,
  BedTransferCreate,
  BedTransferRead,
  BedUpdate,
  FacilityCreate,
  FacilityRead,
  FindDuplicatePatientsApiV1PatientsDuplicatesGetParams,
  HospitalizationCreate,
  HospitalizationRead,
  ListAdmissionsApiV1AdmissionsGetParams,
  PatientCreate,
  PatientRead,
  PatientUpdate,
  ProfessionalCreate,
  ProfessionalRead,
  ProfessionalUpdate,
  RoomCreate,
  RoomRead,
  RoomUpdate,
  ServiceCreate,
  ServiceRead,
  ServiceUpdate,
  SpecialtyCreate,
  SpecialtyRead,
  SpecialtyUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDefault = () => {
/**
 * @summary List Patients
 */
const listPatientsApiV1PatientsGet = (

 options?: SecondParameter<typeof customInstance<PatientRead[]>>,) => {
      return customInstance<PatientRead[]>(
      {url: `/api/v1/patients`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient
 */
const createPatientApiV1PatientsPost = (
    patientCreate: PatientCreate,
 options?: SecondParameter<typeof customInstance<PatientRead>>,) => {
      return customInstance<PatientRead>(
      {url: `/api/v1/patients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientCreate
    },
      options);
    }
  /**
 * @summary Update Patient
 */
const updatePatientApiV1PatientsPatientIdPut = (
    patientId: string,
    patientUpdate: PatientUpdate,
 options?: SecondParameter<typeof customInstance<PatientRead>>,) => {
      return customInstance<PatientRead>(
      {url: `/api/v1/patients/${patientId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: patientUpdate
    },
      options);
    }
  /**
 * @summary Delete Patient
 */
const deletePatientApiV1PatientsPatientIdDelete = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/patients/${patientId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary Find Duplicate Patients
 */
const findDuplicatePatientsApiV1PatientsDuplicatesGet = (
    params: FindDuplicatePatientsApiV1PatientsDuplicatesGetParams,
 options?: SecondParameter<typeof customInstance<PatientRead[]>>,) => {
      return customInstance<PatientRead[]>(
      {url: `/api/v1/patients/duplicates`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary List Specialties
 */
const listSpecialtiesApiV1SpecialtiesGet = (

 options?: SecondParameter<typeof customInstance<SpecialtyRead[]>>,) => {
      return customInstance<SpecialtyRead[]>(
      {url: `/api/v1/specialties`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Specialty
 */
const createSpecialtyApiV1SpecialtiesPost = (
    specialtyCreate: SpecialtyCreate,
 options?: SecondParameter<typeof customInstance<SpecialtyRead>>,) => {
      return customInstance<SpecialtyRead>(
      {url: `/api/v1/specialties`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: specialtyCreate
    },
      options);
    }
  /**
 * @summary Update Specialty
 */
const updateSpecialtyApiV1SpecialtiesSpecialtyIdPut = (
    specialtyId: string,
    specialtyUpdate: SpecialtyUpdate,
 options?: SecondParameter<typeof customInstance<SpecialtyRead>>,) => {
      return customInstance<SpecialtyRead>(
      {url: `/api/v1/specialties/${specialtyId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: specialtyUpdate
    },
      options);
    }
  /**
 * @summary Delete Specialty
 */
const deleteSpecialtyApiV1SpecialtiesSpecialtyIdDelete = (
    specialtyId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/specialties/${specialtyId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Professionals
 */
const listProfessionalsApiV1ProfessionalsGet = (

 options?: SecondParameter<typeof customInstance<ProfessionalRead[]>>,) => {
      return customInstance<ProfessionalRead[]>(
      {url: `/api/v1/professionals`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Professional
 */
const createProfessionalApiV1ProfessionalsPost = (
    professionalCreate: ProfessionalCreate,
 options?: SecondParameter<typeof customInstance<ProfessionalRead>>,) => {
      return customInstance<ProfessionalRead>(
      {url: `/api/v1/professionals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: professionalCreate
    },
      options);
    }
  /**
 * @summary Update Professional
 */
const updateProfessionalApiV1ProfessionalsProfessionalIdPut = (
    professionalId: string,
    professionalUpdate: ProfessionalUpdate,
 options?: SecondParameter<typeof customInstance<ProfessionalRead>>,) => {
      return customInstance<ProfessionalRead>(
      {url: `/api/v1/professionals/${professionalId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: professionalUpdate
    },
      options);
    }
  /**
 * @summary Delete Professional
 */
const deleteProfessionalApiV1ProfessionalsProfessionalIdDelete = (
    professionalId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/professionals/${professionalId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Facilities
 */
const listFacilitiesApiV1FacilitiesGet = (

 options?: SecondParameter<typeof customInstance<FacilityRead[]>>,) => {
      return customInstance<FacilityRead[]>(
      {url: `/api/v1/facilities`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Facility
 */
const createFacilityApiV1FacilitiesPost = (
    facilityCreate: FacilityCreate,
 options?: SecondParameter<typeof customInstance<FacilityRead>>,) => {
      return customInstance<FacilityRead>(
      {url: `/api/v1/facilities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: facilityCreate
    },
      options);
    }
  /**
 * @summary List Services
 */
const listServicesApiV1ServicesGet = (

 options?: SecondParameter<typeof customInstance<ServiceRead[]>>,) => {
      return customInstance<ServiceRead[]>(
      {url: `/api/v1/services`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Service
 */
const createServiceApiV1ServicesPost = (
    serviceCreate: ServiceCreate,
 options?: SecondParameter<typeof customInstance<ServiceRead>>,) => {
      return customInstance<ServiceRead>(
      {url: `/api/v1/services`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: serviceCreate
    },
      options);
    }
  /**
 * @summary Update Service
 */
const updateServiceApiV1ServicesServiceIdPut = (
    serviceId: string,
    serviceUpdate: ServiceUpdate,
 options?: SecondParameter<typeof customInstance<ServiceRead>>,) => {
      return customInstance<ServiceRead>(
      {url: `/api/v1/services/${serviceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: serviceUpdate
    },
      options);
    }
  /**
 * @summary Delete Service
 */
const deleteServiceApiV1ServicesServiceIdDelete = (
    serviceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/services/${serviceId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * Beds board: operational status, patient occupying the bed and reservation holder.
 * @summary List Beds
 */
const listBedsApiV1BedsGet = (

 options?: SecondParameter<typeof customInstance<BedRead[]>>,) => {
      return customInstance<BedRead[]>(
      {url: `/api/v1/beds`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Bed
 */
const createBedApiV1BedsPost = (
    bedCreate: BedCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedCreate
    },
      options);
    }
  /**
 * @summary Update Bed
 */
const updateBedApiV1BedsBedIdPut = (
    bedId: string,
    bedUpdate: BedUpdate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: bedUpdate
    },
      options);
    }
  /**
 * @summary Assign Bed Room
 */
const assignBedRoomApiV1BedsBedIdRoomPost = (
    bedId: string,
    bedRoomAssignmentCreate: BedRoomAssignmentCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}/room`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedRoomAssignmentCreate
    },
      options);
    }
  /**
 * Operational status of a bed. Occupancy and reservation are driven by the
 * hospitalization endpoints and are recorded in ``bed_status_history``.
 * @summary Set Bed Status
 */
const setBedStatusApiV1BedsBedIdStatusPost = (
    bedId: string,
    bedStatusCreate: BedStatusCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedStatusCreate
    },
      options);
    }
  /**
 * @summary List Rooms
 */
const listRoomsApiV1RoomsGet = (

 options?: SecondParameter<typeof customInstance<RoomRead[]>>,) => {
      return customInstance<RoomRead[]>(
      {url: `/api/v1/rooms`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Room
 */
const createRoomApiV1RoomsPost = (
    roomCreate: RoomCreate,
 options?: SecondParameter<typeof customInstance<RoomRead>>,) => {
      return customInstance<RoomRead>(
      {url: `/api/v1/rooms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roomCreate
    },
      options);
    }
  /**
 * @summary Update Room
 */
const updateRoomApiV1RoomsRoomIdPut = (
    roomId: string,
    roomUpdate: RoomUpdate,
 options?: SecondParameter<typeof customInstance<RoomRead>>,) => {
      return customInstance<RoomRead>(
      {url: `/api/v1/rooms/${roomId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roomUpdate
    },
      options);
    }
  /**
 * @summary Delete Room
 */
const deleteRoomApiV1RoomsRoomIdDelete = (
    roomId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/rooms/${roomId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Hospitalizations
 */
const listHospitalizationsApiV1HospitalizationsGet = (

 options?: SecondParameter<typeof customInstance<HospitalizationRead[]>>,) => {
      return customInstance<HospitalizationRead[]>(
      {url: `/api/v1/hospitalizations`, method: 'GET'
    },
      options);
    }
  /**
 * Create the hospitalization of an admission request.
 *
 * An inpatient process cannot exist without the request that justifies it, so the
 * patient, episode, facility and type are taken from ``admission_id``.
 * @summary Create Hospitalization
 */
const createHospitalizationApiV1HospitalizationsPost = (
    hospitalizationCreate: HospitalizationCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationRead>>,) => {
      return customInstance<HospitalizationRead>(
      {url: `/api/v1/hospitalizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationCreate
    },
      options);
    }
  /**
 * @summary List Hospitalization Bed Assignments
 */
const listHospitalizationBedAssignmentsApiV1HospitalizationsHospitalizationIdBedAssignmentsGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead[]>>,) => {
      return customInstance<BedAssignmentRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/bed-assignments`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Assign Bed
 */
const assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost = (
    hospitalizationId: string,
    bedAssignmentCreate: BedAssignmentCreate,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead>>,) => {
      return customInstance<BedAssignmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/bed-assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedAssignmentCreate
    },
      options);
    }
  /**
 * @summary List Admissions
 */
const listAdmissionsApiV1AdmissionsGet = (
    params?: ListAdmissionsApiV1AdmissionsGetParams,
 options?: SecondParameter<typeof customInstance<AdmissionDashboardRead[]>>,) => {
      return customInstance<AdmissionDashboardRead[]>(
      {url: `/api/v1/admissions`, method: 'GET',
        params
    },
      options);
    }
  /**
 * @summary Create Admission
 */
const createAdmissionApiV1AdmissionsPost = (
    admissionCreate: AdmissionCreate,
 options?: SecondParameter<typeof customInstance<AdmissionRead>>,) => {
      return customInstance<AdmissionRead>(
      {url: `/api/v1/admissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: admissionCreate
    },
      options);
    }
  /**
 * @summary Get Admission
 */
const getAdmissionApiV1AdmissionsAdmissionIdGet = (
    admissionId: string,
 options?: SecondParameter<typeof customInstance<AdmissionDashboardRead>>,) => {
      return customInstance<AdmissionDashboardRead>(
      {url: `/api/v1/admissions/${admissionId}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Administrative Discharge
 */
const administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost = (
    admissionId: string,
    administrativeDischargeCreate: AdministrativeDischargeCreate,
 options?: SecondParameter<typeof customInstance<AdmissionRead>>,) => {
      return customInstance<AdmissionRead>(
      {url: `/api/v1/admissions/${admissionId}/administrative-discharge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: administrativeDischargeCreate
    },
      options);
    }
  /**
 * Compatibility endpoint. Registers the clinical discharge, if it is still missing,
 * and the physical departure as separate events. Prefer ``/clinical-discharge`` followed
 * by ``/physical-departure``.
 * @deprecated
 * @summary Release Bed
 */
const releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead>>,) => {
      return customInstance<BedAssignmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/release-bed`, method: 'POST'
    },
      options);
    }
  /**
 * @summary Transfer Bed
 */
const transferBedApiV1HospitalizationsHospitalizationIdTransfersPost = (
    hospitalizationId: string,
    bedTransferCreate: BedTransferCreate,
 options?: SecondParameter<typeof customInstance<BedTransferRead>>,) => {
      return customInstance<BedTransferRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/transfers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedTransferCreate
    },
      options);
    }
  /**
 * @summary List Bed Transfers
 */
const listBedTransfersApiV1HospitalizationsHospitalizationIdTransfersGet = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<BedTransferRead[]>>,) => {
      return customInstance<BedTransferRead[]>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/transfers`, method: 'GET'
    },
      options);
    }
  return {listPatientsApiV1PatientsGet,createPatientApiV1PatientsPost,updatePatientApiV1PatientsPatientIdPut,deletePatientApiV1PatientsPatientIdDelete,findDuplicatePatientsApiV1PatientsDuplicatesGet,listSpecialtiesApiV1SpecialtiesGet,createSpecialtyApiV1SpecialtiesPost,updateSpecialtyApiV1SpecialtiesSpecialtyIdPut,deleteSpecialtyApiV1SpecialtiesSpecialtyIdDelete,listProfessionalsApiV1ProfessionalsGet,createProfessionalApiV1ProfessionalsPost,updateProfessionalApiV1ProfessionalsProfessionalIdPut,deleteProfessionalApiV1ProfessionalsProfessionalIdDelete,listFacilitiesApiV1FacilitiesGet,createFacilityApiV1FacilitiesPost,listServicesApiV1ServicesGet,createServiceApiV1ServicesPost,updateServiceApiV1ServicesServiceIdPut,deleteServiceApiV1ServicesServiceIdDelete,listBedsApiV1BedsGet,createBedApiV1BedsPost,updateBedApiV1BedsBedIdPut,assignBedRoomApiV1BedsBedIdRoomPost,setBedStatusApiV1BedsBedIdStatusPost,listRoomsApiV1RoomsGet,createRoomApiV1RoomsPost,updateRoomApiV1RoomsRoomIdPut,deleteRoomApiV1RoomsRoomIdDelete,listHospitalizationsApiV1HospitalizationsGet,createHospitalizationApiV1HospitalizationsPost,listHospitalizationBedAssignmentsApiV1HospitalizationsHospitalizationIdBedAssignmentsGet,assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost,listAdmissionsApiV1AdmissionsGet,createAdmissionApiV1AdmissionsPost,getAdmissionApiV1AdmissionsAdmissionIdGet,administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost,releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost,transferBedApiV1HospitalizationsHospitalizationIdTransfersPost,listBedTransfersApiV1HospitalizationsHospitalizationIdTransfersGet}};
export type ListPatientsApiV1PatientsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listPatientsApiV1PatientsGet']>>>
export type CreatePatientApiV1PatientsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createPatientApiV1PatientsPost']>>>
export type UpdatePatientApiV1PatientsPatientIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updatePatientApiV1PatientsPatientIdPut']>>>
export type DeletePatientApiV1PatientsPatientIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deletePatientApiV1PatientsPatientIdDelete']>>>
export type FindDuplicatePatientsApiV1PatientsDuplicatesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['findDuplicatePatientsApiV1PatientsDuplicatesGet']>>>
export type ListSpecialtiesApiV1SpecialtiesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listSpecialtiesApiV1SpecialtiesGet']>>>
export type CreateSpecialtyApiV1SpecialtiesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createSpecialtyApiV1SpecialtiesPost']>>>
export type UpdateSpecialtyApiV1SpecialtiesSpecialtyIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateSpecialtyApiV1SpecialtiesSpecialtyIdPut']>>>
export type DeleteSpecialtyApiV1SpecialtiesSpecialtyIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteSpecialtyApiV1SpecialtiesSpecialtyIdDelete']>>>
export type ListProfessionalsApiV1ProfessionalsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listProfessionalsApiV1ProfessionalsGet']>>>
export type CreateProfessionalApiV1ProfessionalsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createProfessionalApiV1ProfessionalsPost']>>>
export type UpdateProfessionalApiV1ProfessionalsProfessionalIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateProfessionalApiV1ProfessionalsProfessionalIdPut']>>>
export type DeleteProfessionalApiV1ProfessionalsProfessionalIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteProfessionalApiV1ProfessionalsProfessionalIdDelete']>>>
export type ListFacilitiesApiV1FacilitiesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listFacilitiesApiV1FacilitiesGet']>>>
export type CreateFacilityApiV1FacilitiesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createFacilityApiV1FacilitiesPost']>>>
export type ListServicesApiV1ServicesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listServicesApiV1ServicesGet']>>>
export type CreateServiceApiV1ServicesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createServiceApiV1ServicesPost']>>>
export type UpdateServiceApiV1ServicesServiceIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateServiceApiV1ServicesServiceIdPut']>>>
export type DeleteServiceApiV1ServicesServiceIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteServiceApiV1ServicesServiceIdDelete']>>>
export type ListBedsApiV1BedsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listBedsApiV1BedsGet']>>>
export type CreateBedApiV1BedsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createBedApiV1BedsPost']>>>
export type UpdateBedApiV1BedsBedIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateBedApiV1BedsBedIdPut']>>>
export type AssignBedRoomApiV1BedsBedIdRoomPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['assignBedRoomApiV1BedsBedIdRoomPost']>>>
export type SetBedStatusApiV1BedsBedIdStatusPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['setBedStatusApiV1BedsBedIdStatusPost']>>>
export type ListRoomsApiV1RoomsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listRoomsApiV1RoomsGet']>>>
export type CreateRoomApiV1RoomsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createRoomApiV1RoomsPost']>>>
export type UpdateRoomApiV1RoomsRoomIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateRoomApiV1RoomsRoomIdPut']>>>
export type DeleteRoomApiV1RoomsRoomIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteRoomApiV1RoomsRoomIdDelete']>>>
export type ListHospitalizationsApiV1HospitalizationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listHospitalizationsApiV1HospitalizationsGet']>>>
export type CreateHospitalizationApiV1HospitalizationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createHospitalizationApiV1HospitalizationsPost']>>>
export type ListHospitalizationBedAssignmentsApiV1HospitalizationsHospitalizationIdBedAssignmentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listHospitalizationBedAssignmentsApiV1HospitalizationsHospitalizationIdBedAssignmentsGet']>>>
export type AssignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost']>>>
export type ListAdmissionsApiV1AdmissionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listAdmissionsApiV1AdmissionsGet']>>>
export type CreateAdmissionApiV1AdmissionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createAdmissionApiV1AdmissionsPost']>>>
export type GetAdmissionApiV1AdmissionsAdmissionIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['getAdmissionApiV1AdmissionsAdmissionIdGet']>>>
export type AdministrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost']>>>
export type ReleaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost']>>>
export type TransferBedApiV1HospitalizationsHospitalizationIdTransfersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['transferBedApiV1HospitalizationsHospitalizationIdTransfersPost']>>>
export type ListBedTransfersApiV1HospitalizationsHospitalizationIdTransfersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listBedTransfersApiV1HospitalizationsHospitalizationIdTransfersGet']>>>
