/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Hospital Internment API
 * OpenAPI spec version: 0.1.0
 */
import type {
  AdministrativeDischargeCreate,
  AdmissionCreate,
  AdmissionDashboardRead,
  AdmissionRead,
  BedAssignmentCreate,
  BedAssignmentRead,
  BedCreate,
  BedRead,
  BedRoomAssignmentCreate,
  BedStatusCreate,
  BedUpdate,
  FacilityCreate,
  FacilityRead,
  HospitalizationCreate,
  HospitalizationRead,
  PatientCoverageCreate,
  PatientCoverageRead,
  PatientCreate,
  PatientRead,
  RoomCreate,
  RoomRead,
  RoomUpdate,
  ServiceCreate,
  ServiceRead,
  ServiceUpdate
} from '../../model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getDefault = () => {
/**
 * @summary List Patients
 */
const listPatientsApiV1PatientsGet = (

 options?: SecondParameter<typeof customInstance<PatientRead[]>>,) => {
      return customInstance<PatientRead[]>(
      {url: `/api/v1/patients`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient
 */
const createPatientApiV1PatientsPost = (
    patientCreate: PatientCreate,
 options?: SecondParameter<typeof customInstance<PatientRead>>,) => {
      return customInstance<PatientRead>(
      {url: `/api/v1/patients`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientCreate
    },
      options);
    }
  /**
 * @summary Find Duplicate Patients
 */
const findDuplicatePatientsApiV1PatientsDuplicatesGet = (
    params: { document_type: string; document_number: string },
 options?: SecondParameter<typeof customInstance<PatientRead[]>>,) => {
      return customInstance<PatientRead[]>(
      {url: `/api/v1/patients/duplicates`, method: 'GET',
      params
    },
      options);
    }
  /**
 * @summary List Patient Coverages
 */
const listPatientCoveragesApiV1PatientsPatientIdCoveragesGet = (
    patientId: string,
 options?: SecondParameter<typeof customInstance<PatientCoverageRead[]>>,) => {
      return customInstance<PatientCoverageRead[]>(
      {url: `/api/v1/patients/${patientId}/coverages`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Patient Coverage
 */
const createPatientCoverageApiV1PatientsPatientIdCoveragesPost = (
    patientId: string,
    patientCoverageCreate: PatientCoverageCreate,
 options?: SecondParameter<typeof customInstance<PatientCoverageRead>>,) => {
      return customInstance<PatientCoverageRead>(
      {url: `/api/v1/patients/${patientId}/coverages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: patientCoverageCreate
    },
      options);
    }
  /**
 * @summary List Facilities
 */
const listFacilitiesApiV1FacilitiesGet = (

 options?: SecondParameter<typeof customInstance<FacilityRead[]>>,) => {
      return customInstance<FacilityRead[]>(
      {url: `/api/v1/facilities`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Facility
 */
const createFacilityApiV1FacilitiesPost = (
    facilityCreate: FacilityCreate,
 options?: SecondParameter<typeof customInstance<FacilityRead>>,) => {
      return customInstance<FacilityRead>(
      {url: `/api/v1/facilities`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: facilityCreate
    },
      options);
    }
  /**
 * @summary List Services
 */
const listServicesApiV1ServicesGet = (

 options?: SecondParameter<typeof customInstance<ServiceRead[]>>,) => {
      return customInstance<ServiceRead[]>(
      {url: `/api/v1/services`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Service
 */
const createServiceApiV1ServicesPost = (
    serviceCreate: ServiceCreate,
 options?: SecondParameter<typeof customInstance<ServiceRead>>,) => {
      return customInstance<ServiceRead>(
      {url: `/api/v1/services`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: serviceCreate
    },
      options);
    }
  /**
 * @summary Update Service
 */
const updateServiceApiV1ServicesServiceIdPut = (
    serviceId: string,
    serviceUpdate: ServiceUpdate,
 options?: SecondParameter<typeof customInstance<ServiceRead>>,) => {
      return customInstance<ServiceRead>(
      {url: `/api/v1/services/${serviceId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: serviceUpdate
    },
      options);
    }
  /**
 * @summary Delete Service
 */
const deleteServiceApiV1ServicesServiceIdDelete = (
    serviceId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/services/${serviceId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Rooms
 */
const listRoomsApiV1RoomsGet = (

 options?: SecondParameter<typeof customInstance<RoomRead[]>>,) => {
      return customInstance<RoomRead[]>(
      {url: `/api/v1/rooms`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Room
 */
const createRoomApiV1RoomsPost = (
    roomCreate: RoomCreate,
 options?: SecondParameter<typeof customInstance<RoomRead>>,) => {
      return customInstance<RoomRead>(
      {url: `/api/v1/rooms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: roomCreate
    },
      options);
    }
  /**
 * @summary Update Room
 */
const updateRoomApiV1RoomsRoomIdPut = (
    roomId: string,
    roomUpdate: RoomUpdate,
 options?: SecondParameter<typeof customInstance<RoomRead>>,) => {
      return customInstance<RoomRead>(
      {url: `/api/v1/rooms/${roomId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: roomUpdate
    },
      options);
    }
  /**
 * @summary Delete Room
 */
const deleteRoomApiV1RoomsRoomIdDelete = (
    roomId: string,
 options?: SecondParameter<typeof customInstance<void>>,) => {
      return customInstance<void>(
      {url: `/api/v1/rooms/${roomId}`, method: 'DELETE'
    },
      options);
    }
  /**
 * @summary List Beds
 */
const listBedsApiV1BedsGet = (

 options?: SecondParameter<typeof customInstance<BedRead[]>>,) => {
      return customInstance<BedRead[]>(
      {url: `/api/v1/beds`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Update Bed
 */
const updateBedApiV1BedsBedIdPut = (
    bedId: string,
    bedUpdate: BedUpdate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: bedUpdate
    },
      options);
    }
  /**
 * @summary Assign Bed Room
 */
const assignBedRoomApiV1BedsBedIdRoomPost = (
    bedId: string,
    bedRoomAssignmentCreate: BedRoomAssignmentCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds/${bedId}/room`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedRoomAssignmentCreate
    },
      options);
    }
  /**
 * @summary Create Bed
 */
const createBedApiV1BedsPost = (
    bedCreate: BedCreate,
 options?: SecondParameter<typeof customInstance<BedRead>>,) => {
      return customInstance<BedRead>(
      {url: `/api/v1/beds`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedCreate
    },
      options);
    }
  /**
 * @summary Set Bed Status
 */
const setBedStatusApiV1BedsBedIdStatusPost = (
    bedId: string,
    bedStatusCreate: BedStatusCreate,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead | null>>,) => {
      return customInstance<BedAssignmentRead | null>(
      {url: `/api/v1/beds/${bedId}/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedStatusCreate
    },
      options);
    }
  /**
 * @summary List Hospitalizations
 */
const listHospitalizationsApiV1HospitalizationsGet = (

 options?: SecondParameter<typeof customInstance<HospitalizationRead[]>>,) => {
      return customInstance<HospitalizationRead[]>(
      {url: `/api/v1/hospitalizations`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Hospitalization
 */
const createHospitalizationApiV1HospitalizationsPost = (
    hospitalizationCreate: HospitalizationCreate,
 options?: SecondParameter<typeof customInstance<HospitalizationRead>>,) => {
      return customInstance<HospitalizationRead>(
      {url: `/api/v1/hospitalizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hospitalizationCreate
    },
      options);
    }
  /**
 * @summary List Admissions
 */
const listAdmissionsApiV1AdmissionsGet = (

 options?: SecondParameter<typeof customInstance<AdmissionDashboardRead[]>>,) => {
      return customInstance<AdmissionDashboardRead[]>(
      {url: `/api/v1/admissions`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Create Admission
 */
const createAdmissionApiV1AdmissionsPost = (
    admissionCreate: AdmissionCreate,
 options?: SecondParameter<typeof customInstance<AdmissionRead>>,) => {
      return customInstance<AdmissionRead>(
      {url: `/api/v1/admissions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: admissionCreate
    },
      options);
    }
  /**
 * @summary Administrative Discharge
 */
const administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost = (
    admissionId: string,
    administrativeDischargeCreate: AdministrativeDischargeCreate,
 options?: SecondParameter<typeof customInstance<AdmissionRead>>,) => {
      return customInstance<AdmissionRead>(
      {url: `/api/v1/admissions/${admissionId}/administrative-discharge`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: administrativeDischargeCreate
    },
      options);
    }
  /**
 * @summary Assign Bed
 */
const assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost = (
    hospitalizationId: string,
    bedAssignmentCreate: BedAssignmentCreate,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead>>,) => {
      return customInstance<BedAssignmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/bed-assignments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bedAssignmentCreate
    },
      options);
    }
  /**
 * @summary Release Bed
 */
const releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost = (
    hospitalizationId: string,
 options?: SecondParameter<typeof customInstance<BedAssignmentRead>>,) => {
      return customInstance<BedAssignmentRead>(
      {url: `/api/v1/hospitalizations/${hospitalizationId}/release-bed`, method: 'POST'
    },
      options);
    }
  return {listPatientsApiV1PatientsGet,createPatientApiV1PatientsPost,findDuplicatePatientsApiV1PatientsDuplicatesGet,listPatientCoveragesApiV1PatientsPatientIdCoveragesGet,createPatientCoverageApiV1PatientsPatientIdCoveragesPost,listFacilitiesApiV1FacilitiesGet,createFacilityApiV1FacilitiesPost,listServicesApiV1ServicesGet,createServiceApiV1ServicesPost,updateServiceApiV1ServicesServiceIdPut,deleteServiceApiV1ServicesServiceIdDelete,listRoomsApiV1RoomsGet,createRoomApiV1RoomsPost,updateRoomApiV1RoomsRoomIdPut,deleteRoomApiV1RoomsRoomIdDelete,listBedsApiV1BedsGet,createBedApiV1BedsPost,updateBedApiV1BedsBedIdPut,assignBedRoomApiV1BedsBedIdRoomPost,setBedStatusApiV1BedsBedIdStatusPost,listHospitalizationsApiV1HospitalizationsGet,createHospitalizationApiV1HospitalizationsPost,listAdmissionsApiV1AdmissionsGet,createAdmissionApiV1AdmissionsPost,administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost,assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost,releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost}};
export type ListPatientsApiV1PatientsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listPatientsApiV1PatientsGet']>>>
export type CreatePatientApiV1PatientsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createPatientApiV1PatientsPost']>>>
export type FindDuplicatePatientsApiV1PatientsDuplicatesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['findDuplicatePatientsApiV1PatientsDuplicatesGet']>>>
export type ListPatientCoveragesApiV1PatientsPatientIdCoveragesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listPatientCoveragesApiV1PatientsPatientIdCoveragesGet']>>>
export type CreatePatientCoverageApiV1PatientsPatientIdCoveragesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createPatientCoverageApiV1PatientsPatientIdCoveragesPost']>>>
export type ListFacilitiesApiV1FacilitiesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listFacilitiesApiV1FacilitiesGet']>>>
export type CreateFacilityApiV1FacilitiesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createFacilityApiV1FacilitiesPost']>>>
export type ListServicesApiV1ServicesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listServicesApiV1ServicesGet']>>>
export type CreateServiceApiV1ServicesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createServiceApiV1ServicesPost']>>>
export type UpdateServiceApiV1ServicesServiceIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateServiceApiV1ServicesServiceIdPut']>>>
export type DeleteServiceApiV1ServicesServiceIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteServiceApiV1ServicesServiceIdDelete']>>>
export type ListRoomsApiV1RoomsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listRoomsApiV1RoomsGet']>>>
export type CreateRoomApiV1RoomsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createRoomApiV1RoomsPost']>>>
export type UpdateRoomApiV1RoomsRoomIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateRoomApiV1RoomsRoomIdPut']>>>
export type DeleteRoomApiV1RoomsRoomIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['deleteRoomApiV1RoomsRoomIdDelete']>>>
export type ListBedsApiV1BedsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listBedsApiV1BedsGet']>>>
export type CreateBedApiV1BedsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createBedApiV1BedsPost']>>>
export type UpdateBedApiV1BedsBedIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['updateBedApiV1BedsBedIdPut']>>>
export type AssignBedRoomApiV1BedsBedIdRoomPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['assignBedRoomApiV1BedsBedIdRoomPost']>>>
export type SetBedStatusApiV1BedsBedIdStatusPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['setBedStatusApiV1BedsBedIdStatusPost']>>>
export type ListHospitalizationsApiV1HospitalizationsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listHospitalizationsApiV1HospitalizationsGet']>>>
export type CreateHospitalizationApiV1HospitalizationsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createHospitalizationApiV1HospitalizationsPost']>>>
export type ListAdmissionsApiV1AdmissionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['listAdmissionsApiV1AdmissionsGet']>>>
export type CreateAdmissionApiV1AdmissionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['createAdmissionApiV1AdmissionsPost']>>>
export type AdministrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['administrativeDischargeApiV1AdmissionsAdmissionIdAdministrativeDischargePost']>>>
export type AssignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['assignBedApiV1HospitalizationsHospitalizationIdBedAssignmentsPost']>>>
export type ReleaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDefault>['releaseBedApiV1HospitalizationsHospitalizationIdReleaseBedPost']>>>
